#ESTOS TOTALES SE CARGARON A PARTIR DE CÁLCULOS GENERADOS EN SRCIPT data_managment.R


###GOBERNADOR
Salta$TotalGob[ Salta$Circuito == "100A" & Salta$Year ==0]<-2481
Salta$TotalGob[ Salta$Circuito == "100A" & Salta$Year ==1]<-2594
Salta$TotalGob[ Salta$Circuito == "101A" & Salta$Year ==0]<-138
Salta$TotalGob[ Salta$Circuito == "101A" & Salta$Year ==1]<-119
Salta$TotalGob[ Salta$Circuito == "102A" & Salta$Year ==0]<-142
Salta$TotalGob[ Salta$Circuito == "102A" & Salta$Year ==1]<-138
Salta$TotalGob[ Salta$Circuito == "103A" & Salta$Year ==0]<-123
Salta$TotalGob[ Salta$Circuito == "103A" & Salta$Year ==1]<-118
Salta$TotalGob[ Salta$Circuito == "103B" & Salta$Year ==0]<-11
Salta$TotalGob[ Salta$Circuito == "103B" & Salta$Year ==1]<-16
Salta$TotalGob[ Salta$Circuito == "10A" & Salta$Year ==0]<-2940
Salta$TotalGob[ Salta$Circuito == "10A" & Salta$Year ==1]<-3099
Salta$TotalGob[ Salta$Circuito == "11A" & Salta$Year ==0]<-2735
Salta$TotalGob[ Salta$Circuito == "11A" & Salta$Year ==1]<-2867
Salta$TotalGob[ Salta$Circuito == "11B" & Salta$Year ==0]<-464
Salta$TotalGob[ Salta$Circuito == "11B" & Salta$Year ==1]<-488
Salta$TotalGob[ Salta$Circuito == "11C" & Salta$Year ==0]<-485
Salta$TotalGob[ Salta$Circuito == "11C" & Salta$Year ==1]<-478
Salta$TotalGob[ Salta$Circuito == "12A" & Salta$Year ==0]<-6264
Salta$TotalGob[ Salta$Circuito == "12A" & Salta$Year ==1]<-5923
Salta$TotalGob[ Salta$Circuito == "12B" & Salta$Year ==0]<-4149
Salta$TotalGob[ Salta$Circuito == "12B" & Salta$Year ==1]<-4949
Salta$TotalGob[ Salta$Circuito == "12C" & Salta$Year ==0]<-4326
Salta$TotalGob[ Salta$Circuito == "12C" & Salta$Year ==1]<-4212
Salta$TotalGob[ Salta$Circuito == "13A" & Salta$Year ==0]<-179
Salta$TotalGob[ Salta$Circuito == "13A" & Salta$Year ==1]<-143
Salta$TotalGob[ Salta$Circuito == "15A" & Salta$Year ==0]<-3063
Salta$TotalGob[ Salta$Circuito == "15A" & Salta$Year ==1]<-2994
Salta$TotalGob[ Salta$Circuito == "15B" & Salta$Year ==0]<-2364
Salta$TotalGob[ Salta$Circuito == "15B" & Salta$Year ==1]<-1606
Salta$TotalGob[ Salta$Circuito == "15C" & Salta$Year ==0]<-3795
Salta$TotalGob[ Salta$Circuito == "15C" & Salta$Year ==1]<-3596
Salta$TotalGob[ Salta$Circuito == "15D" & Salta$Year ==0]<-4175
Salta$TotalGob[ Salta$Circuito == "15D" & Salta$Year ==1]<-4196
Salta$TotalGob[ Salta$Circuito == "15E" & Salta$Year ==0]<-415
Salta$TotalGob[ Salta$Circuito == "15E" & Salta$Year ==1]<-354
Salta$TotalGob[ Salta$Circuito == "15F" & Salta$Year ==0]<-159
Salta$TotalGob[ Salta$Circuito == "15F" & Salta$Year ==1]<-668
Salta$TotalGob[ Salta$Circuito == "15G" & Salta$Year ==0]<-199
Salta$TotalGob[ Salta$Circuito == "15G" & Salta$Year ==1]<-146
Salta$TotalGob[ Salta$Circuito == "16A" & Salta$Year ==0]<-930
Salta$TotalGob[ Salta$Circuito == "16A" & Salta$Year ==1]<-939
Salta$TotalGob[ Salta$Circuito == "16B" & Salta$Year ==0]<-302
Salta$TotalGob[ Salta$Circuito == "16B" & Salta$Year ==1]<-312
Salta$TotalGob[ Salta$Circuito == "17A" & Salta$Year ==0]<-3321
Salta$TotalGob[ Salta$Circuito == "17A" & Salta$Year ==1]<-3367
Salta$TotalGob[ Salta$Circuito == "17B" & Salta$Year ==0]<-290
Salta$TotalGob[ Salta$Circuito == "17B" & Salta$Year ==1]<-319
Salta$TotalGob[ Salta$Circuito == "18A" & Salta$Year ==0]<-287
Salta$TotalGob[ Salta$Circuito == "18A" & Salta$Year ==1]<-275
Salta$TotalGob[ Salta$Circuito == "18B" & Salta$Year ==0]<-583
Salta$TotalGob[ Salta$Circuito == "18B" & Salta$Year ==1]<-619
Salta$TotalGob[ Salta$Circuito == "18C" & Salta$Year ==0]<-159
Salta$TotalGob[ Salta$Circuito == "18C" & Salta$Year ==1]<-123
Salta$TotalGob[ Salta$Circuito == "19A" & Salta$Year ==0]<-64
Salta$TotalGob[ Salta$Circuito == "19A" & Salta$Year ==1]<-92
Salta$TotalGob[ Salta$Circuito == "1A" & Salta$Year ==0]<-3160
Salta$TotalGob[ Salta$Circuito == "1A" & Salta$Year ==1]<-3375
Salta$TotalGob[ Salta$Circuito == "1B" & Salta$Year ==0]<-2859
Salta$TotalGob[ Salta$Circuito == "1B" & Salta$Year ==1]<-2244
Salta$TotalGob[ Salta$Circuito == "1C" & Salta$Year ==0]<-2891
Salta$TotalGob[ Salta$Circuito == "1C" & Salta$Year ==1]<-2777
Salta$TotalGob[ Salta$Circuito == "1D" & Salta$Year ==0]<-3629
Salta$TotalGob[ Salta$Circuito == "1D" & Salta$Year ==1]<-3355
Salta$TotalGob[ Salta$Circuito == "1E" & Salta$Year ==0]<-3401
Salta$TotalGob[ Salta$Circuito == "1E" & Salta$Year ==1]<-3164
Salta$TotalGob[ Salta$Circuito == "1F" & Salta$Year ==0]<-6382
Salta$TotalGob[ Salta$Circuito == "1F" & Salta$Year ==1]<-6743
Salta$TotalGob[ Salta$Circuito == "1G" & Salta$Year ==0]<-5382
Salta$TotalGob[ Salta$Circuito == "1G" & Salta$Year ==1]<-5227
Salta$TotalGob[ Salta$Circuito == "21A" & Salta$Year ==0]<-4377
Salta$TotalGob[ Salta$Circuito == "21A" & Salta$Year ==1]<-4773
Salta$TotalGob[ Salta$Circuito == "21B" & Salta$Year ==0]<-379
Salta$TotalGob[ Salta$Circuito == "21B" & Salta$Year ==1]<-349
Salta$TotalGob[ Salta$Circuito == "22A" & Salta$Year ==0]<-3894
Salta$TotalGob[ Salta$Circuito == "22A" & Salta$Year ==1]<-3836
Salta$TotalGob[ Salta$Circuito == "22B" & Salta$Year ==0]<-288
Salta$TotalGob[ Salta$Circuito == "22B" & Salta$Year ==1]<-251
Salta$TotalGob[ Salta$Circuito == "22C" & Salta$Year ==0]<-604
Salta$TotalGob[ Salta$Circuito == "22C" & Salta$Year ==1]<-581
Salta$TotalGob[ Salta$Circuito == "22D" & Salta$Year ==0]<-393
Salta$TotalGob[ Salta$Circuito == "22D" & Salta$Year ==1]<-497
Salta$TotalGob[ Salta$Circuito == "22E" & Salta$Year ==0]<-781
Salta$TotalGob[ Salta$Circuito == "22E" & Salta$Year ==1]<-853
Salta$TotalGob[ Salta$Circuito == "23A" & Salta$Year ==0]<-183
Salta$TotalGob[ Salta$Circuito == "23A" & Salta$Year ==1]<-136
Salta$TotalGob[ Salta$Circuito == "24A" & Salta$Year ==0]<-7380
Salta$TotalGob[ Salta$Circuito == "24A" & Salta$Year ==1]<-7675
Salta$TotalGob[ Salta$Circuito == "24B" & Salta$Year ==0]<-395
Salta$TotalGob[ Salta$Circuito == "24B" & Salta$Year ==1]<-332
Salta$TotalGob[ Salta$Circuito == "24C" & Salta$Year ==0]<-278
Salta$TotalGob[ Salta$Circuito == "24C" & Salta$Year ==1]<-252
Salta$TotalGob[ Salta$Circuito == "24D" & Salta$Year ==0]<-309
Salta$TotalGob[ Salta$Circuito == "24D" & Salta$Year ==1]<-256
Salta$TotalGob[ Salta$Circuito == "24E" & Salta$Year ==0]<-717
Salta$TotalGob[ Salta$Circuito == "24E" & Salta$Year ==1]<-633
Salta$TotalGob[ Salta$Circuito == "24G" & Salta$Year ==0]<-166
Salta$TotalGob[ Salta$Circuito == "24G" & Salta$Year ==1]<-147
Salta$TotalGob[ Salta$Circuito == "25A" & Salta$Year ==0]<-3888
Salta$TotalGob[ Salta$Circuito == "25A" & Salta$Year ==1]<-3956
Salta$TotalGob[ Salta$Circuito == "25B" & Salta$Year ==0]<-108
Salta$TotalGob[ Salta$Circuito == "25B" & Salta$Year ==1]<-87
Salta$TotalGob[ Salta$Circuito == "25C" & Salta$Year ==0]<-548
Salta$TotalGob[ Salta$Circuito == "25C" & Salta$Year ==1]<-521
Salta$TotalGob[ Salta$Circuito == "25D" & Salta$Year ==0]<-792
Salta$TotalGob[ Salta$Circuito == "25D" & Salta$Year ==1]<-1071
Salta$TotalGob[ Salta$Circuito == "25E" & Salta$Year ==0]<-365
Salta$TotalGob[ Salta$Circuito == "25E" & Salta$Year ==1]<-362
Salta$TotalGob[ Salta$Circuito == "25F" & Salta$Year ==0]<-98
Salta$TotalGob[ Salta$Circuito == "25F" & Salta$Year ==1]<-80
Salta$TotalGob[ Salta$Circuito == "25G" & Salta$Year ==0]<-59
Salta$TotalGob[ Salta$Circuito == "25G" & Salta$Year ==1]<-50
Salta$TotalGob[ Salta$Circuito == "26A" & Salta$Year ==0]<-481
Salta$TotalGob[ Salta$Circuito == "26A" & Salta$Year ==1]<-404
Salta$TotalGob[ Salta$Circuito == "26B" & Salta$Year ==0]<-1479
Salta$TotalGob[ Salta$Circuito == "26B" & Salta$Year ==1]<-1492
Salta$TotalGob[ Salta$Circuito == "27A" & Salta$Year ==0]<-1512
Salta$TotalGob[ Salta$Circuito == "27A" & Salta$Year ==1]<-1531
Salta$TotalGob[ Salta$Circuito == "27B" & Salta$Year ==0]<-359
Salta$TotalGob[ Salta$Circuito == "27B" & Salta$Year ==1]<-352
Salta$TotalGob[ Salta$Circuito == "28A" & Salta$Year ==0]<-180
Salta$TotalGob[ Salta$Circuito == "28A" & Salta$Year ==1]<-210
Salta$TotalGob[ Salta$Circuito == "28B" & Salta$Year ==0]<-2110
Salta$TotalGob[ Salta$Circuito == "28B" & Salta$Year ==1]<-2379
Salta$TotalGob[ Salta$Circuito == "28C" & Salta$Year ==0]<-131
Salta$TotalGob[ Salta$Circuito == "28C" & Salta$Year ==1]<-123
Salta$TotalGob[ Salta$Circuito == "28D" & Salta$Year ==0]<-77
Salta$TotalGob[ Salta$Circuito == "28D" & Salta$Year ==1]<-81
Salta$TotalGob[ Salta$Circuito == "28E" & Salta$Year ==0]<-649
Salta$TotalGob[ Salta$Circuito == "28E" & Salta$Year ==1]<-733
Salta$TotalGob[ Salta$Circuito == "28F" & Salta$Year ==0]<-308
Salta$TotalGob[ Salta$Circuito == "28F" & Salta$Year ==1]<-356
Salta$TotalGob[ Salta$Circuito == "28G" & Salta$Year ==0]<-99
Salta$TotalGob[ Salta$Circuito == "28G" & Salta$Year ==1]<-88
Salta$TotalGob[ Salta$Circuito == "29A" & Salta$Year ==0]<-930
Salta$TotalGob[ Salta$Circuito == "29A" & Salta$Year ==1]<-983
Salta$TotalGob[ Salta$Circuito == "29B" & Salta$Year ==0]<-41
Salta$TotalGob[ Salta$Circuito == "29B" & Salta$Year ==1]<-20
Salta$TotalGob[ Salta$Circuito == "29C" & Salta$Year ==0]<-1861
Salta$TotalGob[ Salta$Circuito == "29C" & Salta$Year ==1]<-1847
Salta$TotalGob[ Salta$Circuito == "29D" & Salta$Year ==0]<-103
Salta$TotalGob[ Salta$Circuito == "29D" & Salta$Year ==1]<-78
Salta$TotalGob[ Salta$Circuito == "29E" & Salta$Year ==0]<-554
Salta$TotalGob[ Salta$Circuito == "29E" & Salta$Year ==1]<-624
Salta$TotalGob[ Salta$Circuito == "29F" & Salta$Year ==0]<-480
Salta$TotalGob[ Salta$Circuito == "29F" & Salta$Year ==1]<-563
Salta$TotalGob[ Salta$Circuito == "29G" & Salta$Year ==0]<-504
Salta$TotalGob[ Salta$Circuito == "29G" & Salta$Year ==1]<-573
Salta$TotalGob[ Salta$Circuito == "29H" & Salta$Year ==0]<-179
Salta$TotalGob[ Salta$Circuito == "29H" & Salta$Year ==1]<-183
Salta$TotalGob[ Salta$Circuito == "2A" & Salta$Year ==0]<-5642
Salta$TotalGob[ Salta$Circuito == "2A" & Salta$Year ==1]<-5300
Salta$TotalGob[ Salta$Circuito == "2B" & Salta$Year ==0]<-3239
Salta$TotalGob[ Salta$Circuito == "2B" & Salta$Year ==1]<-3111
Salta$TotalGob[ Salta$Circuito == "2C" & Salta$Year ==0]<-4392
Salta$TotalGob[ Salta$Circuito == "2C" & Salta$Year ==1]<-3726
Salta$TotalGob[ Salta$Circuito == "2D" & Salta$Year ==0]<-6348
Salta$TotalGob[ Salta$Circuito == "2D" & Salta$Year ==1]<-6305
Salta$TotalGob[ Salta$Circuito == "2E" & Salta$Year ==0]<-2295
Salta$TotalGob[ Salta$Circuito == "2E" & Salta$Year ==1]<-1708
Salta$TotalGob[ Salta$Circuito == "2F" & Salta$Year ==0]<-4857
Salta$TotalGob[ Salta$Circuito == "2F" & Salta$Year ==1]<-4415
Salta$TotalGob[ Salta$Circuito == "2G" & Salta$Year ==0]<-6526
Salta$TotalGob[ Salta$Circuito == "2G" & Salta$Year ==1]<-6583
Salta$TotalGob[ Salta$Circuito == "2H" & Salta$Year ==0]<-1756
Salta$TotalGob[ Salta$Circuito == "2H" & Salta$Year ==1]<-1598
Salta$TotalGob[ Salta$Circuito == "2I" & Salta$Year ==0]<-7097
Salta$TotalGob[ Salta$Circuito == "2I" & Salta$Year ==1]<-6779
Salta$TotalGob[ Salta$Circuito == "2J" & Salta$Year ==0]<-5762
Salta$TotalGob[ Salta$Circuito == "2J" & Salta$Year ==1]<-6050
Salta$TotalGob[ Salta$Circuito == "2K" & Salta$Year ==0]<-4107
Salta$TotalGob[ Salta$Circuito == "2K" & Salta$Year ==1]<-4208
Salta$TotalGob[ Salta$Circuito == "2L" & Salta$Year ==0]<-4385
Salta$TotalGob[ Salta$Circuito == "2L" & Salta$Year ==1]<-4070
Salta$TotalGob[ Salta$Circuito == "2M" & Salta$Year ==0]<-4761
Salta$TotalGob[ Salta$Circuito == "2M" & Salta$Year ==1]<-4970
Salta$TotalGob[ Salta$Circuito == "2N" & Salta$Year ==0]<-5433
Salta$TotalGob[ Salta$Circuito == "2N" & Salta$Year ==1]<-5385
Salta$TotalGob[ Salta$Circuito == "2O" & Salta$Year ==0]<-4961
Salta$TotalGob[ Salta$Circuito == "2O" & Salta$Year ==1]<-5526
Salta$TotalGob[ Salta$Circuito == "2P" & Salta$Year ==0]<-3935
Salta$TotalGob[ Salta$Circuito == "2P" & Salta$Year ==1]<-3874
Salta$TotalGob[ Salta$Circuito == "2Q" & Salta$Year ==0]<-6431
Salta$TotalGob[ Salta$Circuito == "2Q" & Salta$Year ==1]<-6906
Salta$TotalGob[ Salta$Circuito == "30A" & Salta$Year ==0]<-822
Salta$TotalGob[ Salta$Circuito == "30A" & Salta$Year ==1]<-587
Salta$TotalGob[ Salta$Circuito == "30B" & Salta$Year ==0]<-1137
Salta$TotalGob[ Salta$Circuito == "30B" & Salta$Year ==1]<-1122
Salta$TotalGob[ Salta$Circuito == "31A" & Salta$Year ==0]<-18827
Salta$TotalGob[ Salta$Circuito == "31A" & Salta$Year ==1]<-17717
Salta$TotalGob[ Salta$Circuito == "31B" & Salta$Year ==0]<-12014
Salta$TotalGob[ Salta$Circuito == "31B" & Salta$Year ==1]<-11942
Salta$TotalGob[ Salta$Circuito == "31C" & Salta$Year ==0]<-383
Salta$TotalGob[ Salta$Circuito == "31C" & Salta$Year ==1]<-315
Salta$TotalGob[ Salta$Circuito == "32A" & Salta$Year ==0]<-1185
Salta$TotalGob[ Salta$Circuito == "32A" & Salta$Year ==1]<-937
Salta$TotalGob[ Salta$Circuito == "32B" & Salta$Year ==0]<-4975
Salta$TotalGob[ Salta$Circuito == "32B" & Salta$Year ==1]<-5111
Salta$TotalGob[ Salta$Circuito == "33A" & Salta$Year ==0]<-200
Salta$TotalGob[ Salta$Circuito == "33A" & Salta$Year ==1]<-139
Salta$TotalGob[ Salta$Circuito == "33B" & Salta$Year ==0]<-330
Salta$TotalGob[ Salta$Circuito == "33B" & Salta$Year ==1]<-131
Salta$TotalGob[ Salta$Circuito == "34A" & Salta$Year ==0]<-6690
Salta$TotalGob[ Salta$Circuito == "34A" & Salta$Year ==1]<-6168
Salta$TotalGob[ Salta$Circuito == "34B" & Salta$Year ==0]<-67
Salta$TotalGob[ Salta$Circuito == "34B" & Salta$Year ==1]<-45
Salta$TotalGob[ Salta$Circuito == "35A" & Salta$Year ==0]<-1694
Salta$TotalGob[ Salta$Circuito == "35A" & Salta$Year ==1]<-1731
Salta$TotalGob[ Salta$Circuito == "36A" & Salta$Year ==0]<-247
Salta$TotalGob[ Salta$Circuito == "36A" & Salta$Year ==1]<-228
Salta$TotalGob[ Salta$Circuito == "36B" & Salta$Year ==0]<-8974
Salta$TotalGob[ Salta$Circuito == "36B" & Salta$Year ==1]<-9809
Salta$TotalGob[ Salta$Circuito == "37A" & Salta$Year ==0]<-134
Salta$TotalGob[ Salta$Circuito == "37A" & Salta$Year ==1]<-97
Salta$TotalGob[ Salta$Circuito == "38A" & Salta$Year ==0]<-115
Salta$TotalGob[ Salta$Circuito == "38A" & Salta$Year ==1]<-105
Salta$TotalGob[ Salta$Circuito == "38B" & Salta$Year ==0]<-134
Salta$TotalGob[ Salta$Circuito == "38B" & Salta$Year ==1]<-140
Salta$TotalGob[ Salta$Circuito == "39A" & Salta$Year ==0]<-115
Salta$TotalGob[ Salta$Circuito == "39A" & Salta$Year ==1]<-92
Salta$TotalGob[ Salta$Circuito == "3A" & Salta$Year ==0]<-7875
Salta$TotalGob[ Salta$Circuito == "3A" & Salta$Year ==1]<-9136
Salta$TotalGob[ Salta$Circuito == "3B" & Salta$Year ==0]<-12789
Salta$TotalGob[ Salta$Circuito == "3B" & Salta$Year ==1]<-13520
Salta$TotalGob[ Salta$Circuito == "3C" & Salta$Year ==0]<-6032
Salta$TotalGob[ Salta$Circuito == "3C" & Salta$Year ==1]<-6199
Salta$TotalGob[ Salta$Circuito == "3D" & Salta$Year ==0]<-4145
Salta$TotalGob[ Salta$Circuito == "3D" & Salta$Year ==1]<-4445
Salta$TotalGob[ Salta$Circuito == "3E" & Salta$Year ==0]<-4618
Salta$TotalGob[ Salta$Circuito == "3E" & Salta$Year ==1]<-4133
Salta$TotalGob[ Salta$Circuito == "3F" & Salta$Year ==0]<-5290
Salta$TotalGob[ Salta$Circuito == "3F" & Salta$Year ==1]<-4855
Salta$TotalGob[ Salta$Circuito == "3G" & Salta$Year ==0]<-5669
Salta$TotalGob[ Salta$Circuito == "3G" & Salta$Year ==1]<-6004
Salta$TotalGob[ Salta$Circuito == "3H" & Salta$Year ==0]<-6624
Salta$TotalGob[ Salta$Circuito == "3H" & Salta$Year ==1]<-5890
Salta$TotalGob[ Salta$Circuito == "3I" & Salta$Year ==0]<-4638
Salta$TotalGob[ Salta$Circuito == "3I" & Salta$Year ==1]<-6130
Salta$TotalGob[ Salta$Circuito == "3J" & Salta$Year ==0]<-1623
Salta$TotalGob[ Salta$Circuito == "3J" & Salta$Year ==1]<-2114
Salta$TotalGob[ Salta$Circuito == "3K" & Salta$Year ==0]<-1373
Salta$TotalGob[ Salta$Circuito == "3K" & Salta$Year ==1]<-2260
Salta$TotalGob[ Salta$Circuito == "40A" & Salta$Year ==0]<-8887
Salta$TotalGob[ Salta$Circuito == "40A" & Salta$Year ==1]<-9067
Salta$TotalGob[ Salta$Circuito == "40B" & Salta$Year ==0]<-964
Salta$TotalGob[ Salta$Circuito == "40B" & Salta$Year ==1]<-1072
Salta$TotalGob[ Salta$Circuito == "40C" & Salta$Year ==0]<-143
Salta$TotalGob[ Salta$Circuito == "40C" & Salta$Year ==1]<-133
Salta$TotalGob[ Salta$Circuito == "41A" & Salta$Year ==0]<-1101
Salta$TotalGob[ Salta$Circuito == "41A" & Salta$Year ==1]<-1177
Salta$TotalGob[ Salta$Circuito == "41B" & Salta$Year ==0]<-905
Salta$TotalGob[ Salta$Circuito == "41B" & Salta$Year ==1]<-904
Salta$TotalGob[ Salta$Circuito == "41C" & Salta$Year ==0]<-341
Salta$TotalGob[ Salta$Circuito == "41C" & Salta$Year ==1]<-351
Salta$TotalGob[ Salta$Circuito == "41D" & Salta$Year ==0]<-216
Salta$TotalGob[ Salta$Circuito == "41D" & Salta$Year ==1]<-123
Salta$TotalGob[ Salta$Circuito == "42A" & Salta$Year ==0]<-998
Salta$TotalGob[ Salta$Circuito == "42A" & Salta$Year ==1]<-900
Salta$TotalGob[ Salta$Circuito == "42B" & Salta$Year ==0]<-1306
Salta$TotalGob[ Salta$Circuito == "42B" & Salta$Year ==1]<-1320
Salta$TotalGob[ Salta$Circuito == "42C" & Salta$Year ==0]<-7951
Salta$TotalGob[ Salta$Circuito == "42C" & Salta$Year ==1]<-7768
Salta$TotalGob[ Salta$Circuito == "43A" & Salta$Year ==0]<-20782
Salta$TotalGob[ Salta$Circuito == "43A" & Salta$Year ==1]<-20605
Salta$TotalGob[ Salta$Circuito == "43B" & Salta$Year ==0]<-1325
Salta$TotalGob[ Salta$Circuito == "43B" & Salta$Year ==1]<-1148
Salta$TotalGob[ Salta$Circuito == "43C" & Salta$Year ==0]<-2732
Salta$TotalGob[ Salta$Circuito == "43C" & Salta$Year ==1]<-3043
Salta$TotalGob[ Salta$Circuito == "43D" & Salta$Year ==0]<-164
Salta$TotalGob[ Salta$Circuito == "43D" & Salta$Year ==1]<-135
Salta$TotalGob[ Salta$Circuito == "43E" & Salta$Year ==0]<-2536
Salta$TotalGob[ Salta$Circuito == "43E" & Salta$Year ==1]<-2923
Salta$TotalGob[ Salta$Circuito == "43F" & Salta$Year ==0]<-654
Salta$TotalGob[ Salta$Circuito == "43F" & Salta$Year ==1]<-687
Salta$TotalGob[ Salta$Circuito == "44A" & Salta$Year ==0]<-4262
Salta$TotalGob[ Salta$Circuito == "44A" & Salta$Year ==1]<-4448
Salta$TotalGob[ Salta$Circuito == "44B" & Salta$Year ==0]<-376
Salta$TotalGob[ Salta$Circuito == "44B" & Salta$Year ==1]<-413
Salta$TotalGob[ Salta$Circuito == "44C" & Salta$Year ==0]<-467
Salta$TotalGob[ Salta$Circuito == "44C" & Salta$Year ==1]<-535
Salta$TotalGob[ Salta$Circuito == "44D" & Salta$Year ==0]<-443
Salta$TotalGob[ Salta$Circuito == "44D" & Salta$Year ==1]<-394
Salta$TotalGob[ Salta$Circuito == "44E" & Salta$Year ==0]<-457
Salta$TotalGob[ Salta$Circuito == "44E" & Salta$Year ==1]<-500
Salta$TotalGob[ Salta$Circuito == "44F" & Salta$Year ==0]<-279
Salta$TotalGob[ Salta$Circuito == "44F" & Salta$Year ==1]<-287
Salta$TotalGob[ Salta$Circuito == "44G" & Salta$Year ==0]<-227
Salta$TotalGob[ Salta$Circuito == "44G" & Salta$Year ==1]<-230
Salta$TotalGob[ Salta$Circuito == "45A" & Salta$Year ==0]<-8292
Salta$TotalGob[ Salta$Circuito == "45A" & Salta$Year ==1]<-8832
Salta$TotalGob[ Salta$Circuito == "46A" & Salta$Year ==0]<-557
Salta$TotalGob[ Salta$Circuito == "46A" & Salta$Year ==1]<-578
Salta$TotalGob[ Salta$Circuito == "46B" & Salta$Year ==0]<-204
Salta$TotalGob[ Salta$Circuito == "46B" & Salta$Year ==1]<-179
Salta$TotalGob[ Salta$Circuito == "46C" & Salta$Year ==0]<-109
Salta$TotalGob[ Salta$Circuito == "46C" & Salta$Year ==1]<-47
Salta$TotalGob[ Salta$Circuito == "46D" & Salta$Year ==0]<-265
Salta$TotalGob[ Salta$Circuito == "46D" & Salta$Year ==1]<-246
Salta$TotalGob[ Salta$Circuito == "46E" & Salta$Year ==0]<-44
Salta$TotalGob[ Salta$Circuito == "46E" & Salta$Year ==1]<-28
Salta$TotalGob[ Salta$Circuito == "46F" & Salta$Year ==0]<-303
Salta$TotalGob[ Salta$Circuito == "46F" & Salta$Year ==1]<-324
Salta$TotalGob[ Salta$Circuito == "46G" & Salta$Year ==0]<-74
Salta$TotalGob[ Salta$Circuito == "46G" & Salta$Year ==1]<-54
Salta$TotalGob[ Salta$Circuito == "46H" & Salta$Year ==0]<-119
Salta$TotalGob[ Salta$Circuito == "46H" & Salta$Year ==1]<-102
Salta$TotalGob[ Salta$Circuito == "47A" & Salta$Year ==0]<-124
Salta$TotalGob[ Salta$Circuito == "47A" & Salta$Year ==1]<-102
Salta$TotalGob[ Salta$Circuito == "47B" & Salta$Year ==0]<-93
Salta$TotalGob[ Salta$Circuito == "47B" & Salta$Year ==1]<-80
Salta$TotalGob[ Salta$Circuito == "47C" & Salta$Year ==0]<-56
Salta$TotalGob[ Salta$Circuito == "47C" & Salta$Year ==1]<-46
Salta$TotalGob[ Salta$Circuito == "48A" & Salta$Year ==0]<-48
Salta$TotalGob[ Salta$Circuito == "48A" & Salta$Year ==1]<-26
Salta$TotalGob[ Salta$Circuito == "48B" & Salta$Year ==0]<-83
Salta$TotalGob[ Salta$Circuito == "48B" & Salta$Year ==1]<-67
Salta$TotalGob[ Salta$Circuito == "48C" & Salta$Year ==0]<-885
Salta$TotalGob[ Salta$Circuito == "48C" & Salta$Year ==1]<-848
Salta$TotalGob[ Salta$Circuito == "48D" & Salta$Year ==0]<-210
Salta$TotalGob[ Salta$Circuito == "48D" & Salta$Year ==1]<-196
Salta$TotalGob[ Salta$Circuito == "49A" & Salta$Year ==0]<-692
Salta$TotalGob[ Salta$Circuito == "49A" & Salta$Year ==1]<-713
Salta$TotalGob[ Salta$Circuito == "49B" & Salta$Year ==0]<-105
Salta$TotalGob[ Salta$Circuito == "49B" & Salta$Year ==1]<-75
Salta$TotalGob[ Salta$Circuito == "49C" & Salta$Year ==0]<-109
Salta$TotalGob[ Salta$Circuito == "49C" & Salta$Year ==1]<-63
Salta$TotalGob[ Salta$Circuito == "49D" & Salta$Year ==0]<-178
Salta$TotalGob[ Salta$Circuito == "49D" & Salta$Year ==1]<-119
Salta$TotalGob[ Salta$Circuito == "49E" & Salta$Year ==0]<-180
Salta$TotalGob[ Salta$Circuito == "49E" & Salta$Year ==1]<-149
Salta$TotalGob[ Salta$Circuito == "49F" & Salta$Year ==0]<-152
Salta$TotalGob[ Salta$Circuito == "49F" & Salta$Year ==1]<-149
Salta$TotalGob[ Salta$Circuito == "49G" & Salta$Year ==0]<-301
Salta$TotalGob[ Salta$Circuito == "49G" & Salta$Year ==1]<-245
Salta$TotalGob[ Salta$Circuito == "49H" & Salta$Year ==0]<-97
Salta$TotalGob[ Salta$Circuito == "49H" & Salta$Year ==1]<-101
Salta$TotalGob[ Salta$Circuito == "49I" & Salta$Year ==0]<-116
Salta$TotalGob[ Salta$Circuito == "49I" & Salta$Year ==1]<-97
Salta$TotalGob[ Salta$Circuito == "49J" & Salta$Year ==0]<-323
Salta$TotalGob[ Salta$Circuito == "49J" & Salta$Year ==1]<-312
Salta$TotalGob[ Salta$Circuito == "49K" & Salta$Year ==0]<-140
Salta$TotalGob[ Salta$Circuito == "49K" & Salta$Year ==1]<-133
Salta$TotalGob[ Salta$Circuito == "4A" & Salta$Year ==0]<-3942
Salta$TotalGob[ Salta$Circuito == "4A" & Salta$Year ==1]<-4796
Salta$TotalGob[ Salta$Circuito == "4B" & Salta$Year ==0]<-460
Salta$TotalGob[ Salta$Circuito == "4B" & Salta$Year ==1]<-516
Salta$TotalGob[ Salta$Circuito == "4C" & Salta$Year ==0]<-1251
Salta$TotalGob[ Salta$Circuito == "4C" & Salta$Year ==1]<-1822
Salta$TotalGob[ Salta$Circuito == "50A" & Salta$Year ==0]<-905
Salta$TotalGob[ Salta$Circuito == "50A" & Salta$Year ==1]<-983
Salta$TotalGob[ Salta$Circuito == "50B" & Salta$Year ==0]<-285
Salta$TotalGob[ Salta$Circuito == "50B" & Salta$Year ==1]<-278
Salta$TotalGob[ Salta$Circuito == "50C" & Salta$Year ==0]<-126
Salta$TotalGob[ Salta$Circuito == "50C" & Salta$Year ==1]<-120
Salta$TotalGob[ Salta$Circuito == "51A" & Salta$Year ==0]<-715
Salta$TotalGob[ Salta$Circuito == "51A" & Salta$Year ==1]<-745
Salta$TotalGob[ Salta$Circuito == "51B" & Salta$Year ==0]<-93
Salta$TotalGob[ Salta$Circuito == "51B" & Salta$Year ==1]<-386
Salta$TotalGob[ Salta$Circuito == "51D" & Salta$Year ==0]<-133
Salta$TotalGob[ Salta$Circuito == "51D" & Salta$Year ==1]<-142
Salta$TotalGob[ Salta$Circuito == "51E" & Salta$Year ==0]<-60
Salta$TotalGob[ Salta$Circuito == "51E" & Salta$Year ==1]<-44
Salta$TotalGob[ Salta$Circuito == "51F" & Salta$Year ==0]<-48
Salta$TotalGob[ Salta$Circuito == "51F" & Salta$Year ==1]<-64
Salta$TotalGob[ Salta$Circuito == "52A" & Salta$Year ==0]<-3909
Salta$TotalGob[ Salta$Circuito == "52A" & Salta$Year ==1]<-4406
Salta$TotalGob[ Salta$Circuito == "52B" & Salta$Year ==0]<-2591
Salta$TotalGob[ Salta$Circuito == "52B" & Salta$Year ==1]<-2958
Salta$TotalGob[ Salta$Circuito == "52C" & Salta$Year ==0]<-351
Salta$TotalGob[ Salta$Circuito == "52C" & Salta$Year ==1]<-387
Salta$TotalGob[ Salta$Circuito == "52D" & Salta$Year ==0]<-262
Salta$TotalGob[ Salta$Circuito == "52D" & Salta$Year ==1]<-251
Salta$TotalGob[ Salta$Circuito == "53A" & Salta$Year ==0]<-1426
Salta$TotalGob[ Salta$Circuito == "53A" & Salta$Year ==1]<-1701
Salta$TotalGob[ Salta$Circuito == "53B" & Salta$Year ==0]<-570
Salta$TotalGob[ Salta$Circuito == "53B" & Salta$Year ==1]<-999
Salta$TotalGob[ Salta$Circuito == "54A" & Salta$Year ==0]<-4024
Salta$TotalGob[ Salta$Circuito == "54A" & Salta$Year ==1]<-4294
Salta$TotalGob[ Salta$Circuito == "54B" & Salta$Year ==0]<-178
Salta$TotalGob[ Salta$Circuito == "54B" & Salta$Year ==1]<-161
Salta$TotalGob[ Salta$Circuito == "55A" & Salta$Year ==0]<-574
Salta$TotalGob[ Salta$Circuito == "55A" & Salta$Year ==1]<-661
Salta$TotalGob[ Salta$Circuito == "55B" & Salta$Year ==0]<-236
Salta$TotalGob[ Salta$Circuito == "55B" & Salta$Year ==1]<-246
Salta$TotalGob[ Salta$Circuito == "55C" & Salta$Year ==0]<-118
Salta$TotalGob[ Salta$Circuito == "55C" & Salta$Year ==1]<-120
Salta$TotalGob[ Salta$Circuito == "59A" & Salta$Year ==0]<-1508
Salta$TotalGob[ Salta$Circuito == "59A" & Salta$Year ==1]<-1575
Salta$TotalGob[ Salta$Circuito == "5A" & Salta$Year ==0]<-4403
Salta$TotalGob[ Salta$Circuito == "5A" & Salta$Year ==1]<-5066
Salta$TotalGob[ Salta$Circuito == "5B" & Salta$Year ==0]<-4322
Salta$TotalGob[ Salta$Circuito == "5B" & Salta$Year ==1]<-4159
Salta$TotalGob[ Salta$Circuito == "5C" & Salta$Year ==0]<-4183
Salta$TotalGob[ Salta$Circuito == "5C" & Salta$Year ==1]<-5087
Salta$TotalGob[ Salta$Circuito == "5D" & Salta$Year ==0]<-3809
Salta$TotalGob[ Salta$Circuito == "5D" & Salta$Year ==1]<-4566
Salta$TotalGob[ Salta$Circuito == "5E" & Salta$Year ==0]<-7253
Salta$TotalGob[ Salta$Circuito == "5E" & Salta$Year ==1]<-9156
Salta$TotalGob[ Salta$Circuito == "5F" & Salta$Year ==0]<-5604
Salta$TotalGob[ Salta$Circuito == "5F" & Salta$Year ==1]<-6572
Salta$TotalGob[ Salta$Circuito == "5G" & Salta$Year ==0]<-6334
Salta$TotalGob[ Salta$Circuito == "5G" & Salta$Year ==1]<-6591
Salta$TotalGob[ Salta$Circuito == "5H" & Salta$Year ==0]<-2937
Salta$TotalGob[ Salta$Circuito == "5H" & Salta$Year ==1]<-3245
Salta$TotalGob[ Salta$Circuito == "5I" & Salta$Year ==0]<-7509
Salta$TotalGob[ Salta$Circuito == "5I" & Salta$Year ==1]<-8157
Salta$TotalGob[ Salta$Circuito == "5J" & Salta$Year ==0]<-449
Salta$TotalGob[ Salta$Circuito == "5J" & Salta$Year ==1]<-470
Salta$TotalGob[ Salta$Circuito == "5K" & Salta$Year ==0]<-874
Salta$TotalGob[ Salta$Circuito == "5K" & Salta$Year ==1]<-1100
Salta$TotalGob[ Salta$Circuito == "5L" & Salta$Year ==0]<-4395
Salta$TotalGob[ Salta$Circuito == "5L" & Salta$Year ==1]<-5479
Salta$TotalGob[ Salta$Circuito == "5M" & Salta$Year ==0]<-741
Salta$TotalGob[ Salta$Circuito == "5M" & Salta$Year ==1]<-1644
Salta$TotalGob[ Salta$Circuito == "5N" & Salta$Year ==0]<-2099
Salta$TotalGob[ Salta$Circuito == "5N" & Salta$Year ==1]<-3624
Salta$TotalGob[ Salta$Circuito == "60A" & Salta$Year ==0]<-249
Salta$TotalGob[ Salta$Circuito == "60A" & Salta$Year ==1]<-238
Salta$TotalGob[ Salta$Circuito == "61A" & Salta$Year ==0]<-2461
Salta$TotalGob[ Salta$Circuito == "61A" & Salta$Year ==1]<-2563
Salta$TotalGob[ Salta$Circuito == "62A" & Salta$Year ==0]<-239
Salta$TotalGob[ Salta$Circuito == "62A" & Salta$Year ==1]<-183
Salta$TotalGob[ Salta$Circuito == "63A" & Salta$Year ==0]<-1413
Salta$TotalGob[ Salta$Circuito == "63A" & Salta$Year ==1]<-1578
Salta$TotalGob[ Salta$Circuito == "64A" & Salta$Year ==0]<-24
Salta$TotalGob[ Salta$Circuito == "64A" & Salta$Year ==1]<-19
Salta$TotalGob[ Salta$Circuito == "64B" & Salta$Year ==0]<-70
Salta$TotalGob[ Salta$Circuito == "64B" & Salta$Year ==1]<-73
Salta$TotalGob[ Salta$Circuito == "65A" & Salta$Year ==0]<-83
Salta$TotalGob[ Salta$Circuito == "65A" & Salta$Year ==1]<-82
Salta$TotalGob[ Salta$Circuito == "65B" & Salta$Year ==0]<-100
Salta$TotalGob[ Salta$Circuito == "65B" & Salta$Year ==1]<-90
Salta$TotalGob[ Salta$Circuito == "66A" & Salta$Year ==0]<-143
Salta$TotalGob[ Salta$Circuito == "66A" & Salta$Year ==1]<-150
Salta$TotalGob[ Salta$Circuito == "66B" & Salta$Year ==0]<-155
Salta$TotalGob[ Salta$Circuito == "66B" & Salta$Year ==1]<-142
Salta$TotalGob[ Salta$Circuito == "67A" & Salta$Year ==0]<-9519
Salta$TotalGob[ Salta$Circuito == "67A" & Salta$Year ==1]<-8921
Salta$TotalGob[ Salta$Circuito == "67B" & Salta$Year ==0]<-2376
Salta$TotalGob[ Salta$Circuito == "67B" & Salta$Year ==1]<-2909
Salta$TotalGob[ Salta$Circuito == "67C" & Salta$Year ==0]<-282
Salta$TotalGob[ Salta$Circuito == "67C" & Salta$Year ==1]<-175
Salta$TotalGob[ Salta$Circuito == "67D" & Salta$Year ==0]<-317
Salta$TotalGob[ Salta$Circuito == "67D" & Salta$Year ==1]<-232
Salta$TotalGob[ Salta$Circuito == "67E" & Salta$Year ==0]<-147
Salta$TotalGob[ Salta$Circuito == "67E" & Salta$Year ==1]<-117
Salta$TotalGob[ Salta$Circuito == "67F" & Salta$Year ==0]<-71
Salta$TotalGob[ Salta$Circuito == "67F" & Salta$Year ==1]<-47
Salta$TotalGob[ Salta$Circuito == "67G" & Salta$Year ==0]<-120
Salta$TotalGob[ Salta$Circuito == "67G" & Salta$Year ==1]<-89
Salta$TotalGob[ Salta$Circuito == "67H" & Salta$Year ==0]<-113
Salta$TotalGob[ Salta$Circuito == "67H" & Salta$Year ==1]<-95
Salta$TotalGob[ Salta$Circuito == "68A" & Salta$Year ==0]<-91
Salta$TotalGob[ Salta$Circuito == "68A" & Salta$Year ==1]<-48
Salta$TotalGob[ Salta$Circuito == "68B" & Salta$Year ==0]<-96
Salta$TotalGob[ Salta$Circuito == "68B" & Salta$Year ==1]<-62
Salta$TotalGob[ Salta$Circuito == "68C" & Salta$Year ==0]<-67
Salta$TotalGob[ Salta$Circuito == "68C" & Salta$Year ==1]<-26
Salta$TotalGob[ Salta$Circuito == "69A" & Salta$Year ==0]<-119
Salta$TotalGob[ Salta$Circuito == "69A" & Salta$Year ==1]<-71
Salta$TotalGob[ Salta$Circuito == "6A" & Salta$Year ==0]<-3269
Salta$TotalGob[ Salta$Circuito == "6A" & Salta$Year ==1]<-3629
Salta$TotalGob[ Salta$Circuito == "70A" & Salta$Year ==0]<-119
Salta$TotalGob[ Salta$Circuito == "70A" & Salta$Year ==1]<-72
Salta$TotalGob[ Salta$Circuito == "70B" & Salta$Year ==0]<-139
Salta$TotalGob[ Salta$Circuito == "70B" & Salta$Year ==1]<-99
Salta$TotalGob[ Salta$Circuito == "71A" & Salta$Year ==0]<-467
Salta$TotalGob[ Salta$Circuito == "71A" & Salta$Year ==1]<-349
Salta$TotalGob[ Salta$Circuito == "71B" & Salta$Year ==0]<-76
Salta$TotalGob[ Salta$Circuito == "71B" & Salta$Year ==1]<-60
Salta$TotalGob[ Salta$Circuito == "72A" & Salta$Year ==0]<-378
Salta$TotalGob[ Salta$Circuito == "72A" & Salta$Year ==1]<-361
Salta$TotalGob[ Salta$Circuito == "72B" & Salta$Year ==0]<-114
Salta$TotalGob[ Salta$Circuito == "72B" & Salta$Year ==1]<-67
Salta$TotalGob[ Salta$Circuito == "72C" & Salta$Year ==0]<-331
Salta$TotalGob[ Salta$Circuito == "72C" & Salta$Year ==1]<-291
Salta$TotalGob[ Salta$Circuito == "72D" & Salta$Year ==0]<-194
Salta$TotalGob[ Salta$Circuito == "72D" & Salta$Year ==1]<-173
Salta$TotalGob[ Salta$Circuito == "73A" & Salta$Year ==0]<-515
Salta$TotalGob[ Salta$Circuito == "73A" & Salta$Year ==1]<-534
Salta$TotalGob[ Salta$Circuito == "73B" & Salta$Year ==0]<-236
Salta$TotalGob[ Salta$Circuito == "73B" & Salta$Year ==1]<-240
Salta$TotalGob[ Salta$Circuito == "74A" & Salta$Year ==0]<-1672
Salta$TotalGob[ Salta$Circuito == "74A" & Salta$Year ==1]<-1732
Salta$TotalGob[ Salta$Circuito == "75A" & Salta$Year ==0]<-952
Salta$TotalGob[ Salta$Circuito == "75A" & Salta$Year ==1]<-995
Salta$TotalGob[ Salta$Circuito == "75B" & Salta$Year ==0]<-211
Salta$TotalGob[ Salta$Circuito == "75B" & Salta$Year ==1]<-191
Salta$TotalGob[ Salta$Circuito == "79A" & Salta$Year ==0]<-1271
Salta$TotalGob[ Salta$Circuito == "79A" & Salta$Year ==1]<-1323
Salta$TotalGob[ Salta$Circuito == "79B" & Salta$Year ==0]<-921
Salta$TotalGob[ Salta$Circuito == "79B" & Salta$Year ==1]<-943
Salta$TotalGob[ Salta$Circuito == "79C" & Salta$Year ==0]<-207
Salta$TotalGob[ Salta$Circuito == "79C" & Salta$Year ==1]<-197
Salta$TotalGob[ Salta$Circuito == "7A" & Salta$Year ==0]<-101
Salta$TotalGob[ Salta$Circuito == "7A" & Salta$Year ==1]<-82
Salta$TotalGob[ Salta$Circuito == "80A" & Salta$Year ==0]<-110
Salta$TotalGob[ Salta$Circuito == "80A" & Salta$Year ==1]<-90
Salta$TotalGob[ Salta$Circuito == "81A" & Salta$Year ==0]<-233
Salta$TotalGob[ Salta$Circuito == "81A" & Salta$Year ==1]<-211
Salta$TotalGob[ Salta$Circuito == "82A" & Salta$Year ==0]<-668
Salta$TotalGob[ Salta$Circuito == "82A" & Salta$Year ==1]<-624
Salta$TotalGob[ Salta$Circuito == "82B" & Salta$Year ==0]<-109
Salta$TotalGob[ Salta$Circuito == "82B" & Salta$Year ==1]<-84
Salta$TotalGob[ Salta$Circuito == "83A" & Salta$Year ==0]<-155
Salta$TotalGob[ Salta$Circuito == "83A" & Salta$Year ==1]<-118
Salta$TotalGob[ Salta$Circuito == "83B" & Salta$Year ==0]<-252
Salta$TotalGob[ Salta$Circuito == "83B" & Salta$Year ==1]<-214
Salta$TotalGob[ Salta$Circuito == "84A" & Salta$Year ==0]<-664
Salta$TotalGob[ Salta$Circuito == "84A" & Salta$Year ==1]<-737
Salta$TotalGob[ Salta$Circuito == "85A" & Salta$Year ==0]<-609
Salta$TotalGob[ Salta$Circuito == "85A" & Salta$Year ==1]<-655
Salta$TotalGob[ Salta$Circuito == "85B" & Salta$Year ==0]<-94
Salta$TotalGob[ Salta$Circuito == "85B" & Salta$Year ==1]<-81
Salta$TotalGob[ Salta$Circuito == "86A" & Salta$Year ==0]<-597
Salta$TotalGob[ Salta$Circuito == "86A" & Salta$Year ==1]<-579
Salta$TotalGob[ Salta$Circuito == "87A" & Salta$Year ==0]<-336
Salta$TotalGob[ Salta$Circuito == "87A" & Salta$Year ==1]<-375
Salta$TotalGob[ Salta$Circuito == "88A" & Salta$Year ==0]<-188
Salta$TotalGob[ Salta$Circuito == "88A" & Salta$Year ==1]<-179
Salta$TotalGob[ Salta$Circuito == "88B" & Salta$Year ==0]<-68
Salta$TotalGob[ Salta$Circuito == "88B" & Salta$Year ==1]<-66
Salta$TotalGob[ Salta$Circuito == "88C" & Salta$Year ==0]<-272
Salta$TotalGob[ Salta$Circuito == "88C" & Salta$Year ==1]<-278
Salta$TotalGob[ Salta$Circuito == "8A" & Salta$Year ==0]<-1384
Salta$TotalGob[ Salta$Circuito == "8A" & Salta$Year ==1]<-1624
Salta$TotalGob[ Salta$Circuito == "8B" & Salta$Year ==0]<-122
Salta$TotalGob[ Salta$Circuito == "8B" & Salta$Year ==1]<-109
Salta$TotalGob[ Salta$Circuito == "8C" & Salta$Year ==0]<-123
Salta$TotalGob[ Salta$Circuito == "8C" & Salta$Year ==1]<-93
Salta$TotalGob[ Salta$Circuito == "91A" & Salta$Year ==0]<-9479
Salta$TotalGob[ Salta$Circuito == "91A" & Salta$Year ==1]<-10007
Salta$TotalGob[ Salta$Circuito == "91B" & Salta$Year ==0]<-436
Salta$TotalGob[ Salta$Circuito == "91B" & Salta$Year ==1]<-362
Salta$TotalGob[ Salta$Circuito == "91C" & Salta$Year ==0]<-219
Salta$TotalGob[ Salta$Circuito == "91C" & Salta$Year ==1]<-185
Salta$TotalGob[ Salta$Circuito == "91D" & Salta$Year ==0]<-164
Salta$TotalGob[ Salta$Circuito == "91D" & Salta$Year ==1]<-203
Salta$TotalGob[ Salta$Circuito == "92A" & Salta$Year ==0]<-162
Salta$TotalGob[ Salta$Circuito == "92A" & Salta$Year ==1]<-136
Salta$TotalGob[ Salta$Circuito == "93A" & Salta$Year ==0]<-4531
Salta$TotalGob[ Salta$Circuito == "93A" & Salta$Year ==1]<-5047
Salta$TotalGob[ Salta$Circuito == "93B" & Salta$Year ==0]<-84
Salta$TotalGob[ Salta$Circuito == "93B" & Salta$Year ==1]<-83
Salta$TotalGob[ Salta$Circuito == "94A" & Salta$Year ==0]<-172
Salta$TotalGob[ Salta$Circuito == "94A" & Salta$Year ==1]<-145
Salta$TotalGob[ Salta$Circuito == "95A" & Salta$Year ==0]<-1547
Salta$TotalGob[ Salta$Circuito == "95A" & Salta$Year ==1]<-1723
Salta$TotalGob[ Salta$Circuito == "96B" & Salta$Year ==0]<-113
Salta$TotalGob[ Salta$Circuito == "96B" & Salta$Year ==1]<-73
Salta$TotalGob[ Salta$Circuito == "97A" & Salta$Year ==0]<-109
Salta$TotalGob[ Salta$Circuito == "97A" & Salta$Year ==1]<-92
Salta$TotalGob[ Salta$Circuito == "97B" & Salta$Year ==0]<-110
Salta$TotalGob[ Salta$Circuito == "97B" & Salta$Year ==1]<-99
Salta$TotalGob[ Salta$Circuito == "97C" & Salta$Year ==0]<-97
Salta$TotalGob[ Salta$Circuito == "97C" & Salta$Year ==1]<-95
Salta$TotalGob[ Salta$Circuito == "97D" & Salta$Year ==0]<-50
Salta$TotalGob[ Salta$Circuito == "97D" & Salta$Year ==1]<-34
Salta$TotalGob[ Salta$Circuito == "98A" & Salta$Year ==0]<-62
Salta$TotalGob[ Salta$Circuito == "98A" & Salta$Year ==1]<-60
Salta$TotalGob[ Salta$Circuito == "99A" & Salta$Year ==0]<-506
Salta$TotalGob[ Salta$Circuito == "99A" & Salta$Year ==1]<-576
Salta$TotalGob[ Salta$Circuito == "99B" & Salta$Year ==0]<-207
Salta$TotalGob[ Salta$Circuito == "99B" & Salta$Year ==1]<-212
Salta$TotalGob[ Salta$Circuito == "99C" & Salta$Year ==0]<-304
Salta$TotalGob[ Salta$Circuito == "99C" & Salta$Year ==1]<-277
Salta$TotalGob[ Salta$Circuito == "9A" & Salta$Year ==0]<-2663
Salta$TotalGob[ Salta$Circuito == "9A" & Salta$Year ==1]<-3262
Salta$TotalGob[ Salta$Circuito == "9B" & Salta$Year ==0]<-205
Salta$TotalGob[ Salta$Circuito == "9B" & Salta$Year ==1]<-205

#LEGISLADOR
Salta$TotalLeg[ Salta$Circuito == "100A" & Salta$Year ==0]<-2481
Salta$TotalLeg[ Salta$Circuito == "101A" & Salta$Year ==0]<-138
Salta$TotalLeg[ Salta$Circuito == "102A" & Salta$Year ==0]<-142
Salta$TotalLeg[ Salta$Circuito == "103A" & Salta$Year ==0]<-123
Salta$TotalLeg[ Salta$Circuito == "103B" & Salta$Year ==0]<-11
Salta$TotalLeg[ Salta$Circuito == "10A" & Salta$Year ==0]<-2942
Salta$TotalLeg[ Salta$Circuito == "11A" & Salta$Year ==0]<-2735
Salta$TotalLeg[ Salta$Circuito == "11B" & Salta$Year ==0]<-464
Salta$TotalLeg[ Salta$Circuito == "11C" & Salta$Year ==0]<-485
Salta$TotalLeg[ Salta$Circuito == "12A" & Salta$Year ==0]<-6268
Salta$TotalLeg[ Salta$Circuito == "12B" & Salta$Year ==0]<-4149
Salta$TotalLeg[ Salta$Circuito == "12C" & Salta$Year ==0]<-4326
Salta$TotalLeg[ Salta$Circuito == "13A" & Salta$Year ==0]<-179
Salta$TotalLeg[ Salta$Circuito == "16A" & Salta$Year ==0]<-930
Salta$TotalLeg[ Salta$Circuito == "16B" & Salta$Year ==0]<-302
Salta$TotalLeg[ Salta$Circuito == "17A" & Salta$Year ==0]<-3321
Salta$TotalLeg[ Salta$Circuito == "17B" & Salta$Year ==0]<-290
Salta$TotalLeg[ Salta$Circuito == "18A" & Salta$Year ==0]<-287
Salta$TotalLeg[ Salta$Circuito == "18B" & Salta$Year ==0]<-583
Salta$TotalLeg[ Salta$Circuito == "18C" & Salta$Year ==0]<-159
Salta$TotalLeg[ Salta$Circuito == "19A" & Salta$Year ==0]<-64
Salta$TotalLeg[ Salta$Circuito == "21A" & Salta$Year ==0]<-4377
Salta$TotalLeg[ Salta$Circuito == "21B" & Salta$Year ==0]<-379
Salta$TotalLeg[ Salta$Circuito == "22A" & Salta$Year ==0]<-3894
Salta$TotalLeg[ Salta$Circuito == "22B" & Salta$Year ==0]<-288
Salta$TotalLeg[ Salta$Circuito == "22C" & Salta$Year ==0]<-604
Salta$TotalLeg[ Salta$Circuito == "22D" & Salta$Year ==0]<-393
Salta$TotalLeg[ Salta$Circuito == "22E" & Salta$Year ==0]<-781
Salta$TotalLeg[ Salta$Circuito == "23A" & Salta$Year ==0]<-183
Salta$TotalLeg[ Salta$Circuito == "24A" & Salta$Year ==0]<-7382
Salta$TotalLeg[ Salta$Circuito == "24B" & Salta$Year ==0]<-395
Salta$TotalLeg[ Salta$Circuito == "24C" & Salta$Year ==0]<-278
Salta$TotalLeg[ Salta$Circuito == "24D" & Salta$Year ==0]<-309
Salta$TotalLeg[ Salta$Circuito == "24E" & Salta$Year ==0]<-717
Salta$TotalLeg[ Salta$Circuito == "24G" & Salta$Year ==0]<-166
Salta$TotalLeg[ Salta$Circuito == "25A" & Salta$Year ==0]<-3888
Salta$TotalLeg[ Salta$Circuito == "25B" & Salta$Year ==0]<-108
Salta$TotalLeg[ Salta$Circuito == "25C" & Salta$Year ==0]<-548
Salta$TotalLeg[ Salta$Circuito == "25D" & Salta$Year ==0]<-792
Salta$TotalLeg[ Salta$Circuito == "25E" & Salta$Year ==0]<-365
Salta$TotalLeg[ Salta$Circuito == "25F" & Salta$Year ==0]<-98
Salta$TotalLeg[ Salta$Circuito == "25G" & Salta$Year ==0]<-59
Salta$TotalLeg[ Salta$Circuito == "26A" & Salta$Year ==0]<-481
Salta$TotalLeg[ Salta$Circuito == "26B" & Salta$Year ==0]<-1479
Salta$TotalLeg[ Salta$Circuito == "27A" & Salta$Year ==0]<-1512
Salta$TotalLeg[ Salta$Circuito == "27B" & Salta$Year ==0]<-359
Salta$TotalLeg[ Salta$Circuito == "28A" & Salta$Year ==0]<-180
Salta$TotalLeg[ Salta$Circuito == "28B" & Salta$Year ==0]<-2109
Salta$TotalLeg[ Salta$Circuito == "28C" & Salta$Year ==0]<-131
Salta$TotalLeg[ Salta$Circuito == "28D" & Salta$Year ==0]<-77
Salta$TotalLeg[ Salta$Circuito == "28E" & Salta$Year ==0]<-649
Salta$TotalLeg[ Salta$Circuito == "28F" & Salta$Year ==0]<-308
Salta$TotalLeg[ Salta$Circuito == "28G" & Salta$Year ==0]<-99
Salta$TotalLeg[ Salta$Circuito == "29A" & Salta$Year ==0]<-930
Salta$TotalLeg[ Salta$Circuito == "29B" & Salta$Year ==0]<-41
Salta$TotalLeg[ Salta$Circuito == "29C" & Salta$Year ==0]<-1861
Salta$TotalLeg[ Salta$Circuito == "29D" & Salta$Year ==0]<-103
Salta$TotalLeg[ Salta$Circuito == "29E" & Salta$Year ==0]<-554
Salta$TotalLeg[ Salta$Circuito == "29F" & Salta$Year ==0]<-480
Salta$TotalLeg[ Salta$Circuito == "29G" & Salta$Year ==0]<-504
Salta$TotalLeg[ Salta$Circuito == "29H" & Salta$Year ==0]<-178
Salta$TotalLeg[ Salta$Circuito == "2D" & Salta$Year ==0]<-6354
Salta$TotalLeg[ Salta$Circuito == "2G" & Salta$Year ==0]<-6527
Salta$TotalLeg[ Salta$Circuito == "2H" & Salta$Year ==0]<-1756
Salta$TotalLeg[ Salta$Circuito == "2I" & Salta$Year ==0]<-7106
Salta$TotalLeg[ Salta$Circuito == "2J" & Salta$Year ==0]<-5760
Salta$TotalLeg[ Salta$Circuito == "2K" & Salta$Year ==0]<-4112
Salta$TotalLeg[ Salta$Circuito == "2L" & Salta$Year ==0]<-4391
Salta$TotalLeg[ Salta$Circuito == "2N" & Salta$Year ==0]<-5439
Salta$TotalLeg[ Salta$Circuito == "2O" & Salta$Year ==0]<-4959
Salta$TotalLeg[ Salta$Circuito == "2P" & Salta$Year ==0]<-3921
Salta$TotalLeg[ Salta$Circuito == "2Q" & Salta$Year ==0]<-6449
Salta$TotalLeg[ Salta$Circuito == "32A" & Salta$Year ==0]<-1185
Salta$TotalLeg[ Salta$Circuito == "32B" & Salta$Year ==0]<-4976
Salta$TotalLeg[ Salta$Circuito == "34A" & Salta$Year ==0]<-6690
Salta$TotalLeg[ Salta$Circuito == "34B" & Salta$Year ==0]<-67
Salta$TotalLeg[ Salta$Circuito == "35A" & Salta$Year ==0]<-1694
Salta$TotalLeg[ Salta$Circuito == "36A" & Salta$Year ==0]<-247
Salta$TotalLeg[ Salta$Circuito == "36B" & Salta$Year ==0]<-8974
Salta$TotalLeg[ Salta$Circuito == "37A" & Salta$Year ==0]<-134
Salta$TotalLeg[ Salta$Circuito == "38A" & Salta$Year ==0]<-115
Salta$TotalLeg[ Salta$Circuito == "38B" & Salta$Year ==0]<-134
Salta$TotalLeg[ Salta$Circuito == "39A" & Salta$Year ==0]<-115
Salta$TotalLeg[ Salta$Circuito == "3G" & Salta$Year ==0]<-5669
Salta$TotalLeg[ Salta$Circuito == "3H" & Salta$Year ==0]<-6627
Salta$TotalLeg[ Salta$Circuito == "3I" & Salta$Year ==0]<-4638
Salta$TotalLeg[ Salta$Circuito == "3J" & Salta$Year ==0]<-1623
Salta$TotalLeg[ Salta$Circuito == "40A" & Salta$Year ==0]<-8890.5
Salta$TotalLeg[ Salta$Circuito == "40B" & Salta$Year ==0]<-964
Salta$TotalLeg[ Salta$Circuito == "40C" & Salta$Year ==0]<-143
Salta$TotalLeg[ Salta$Circuito == "41A" & Salta$Year ==0]<-1102
Salta$TotalLeg[ Salta$Circuito == "41B" & Salta$Year ==0]<-905
Salta$TotalLeg[ Salta$Circuito == "41C" & Salta$Year ==0]<-341
Salta$TotalLeg[ Salta$Circuito == "41D" & Salta$Year ==0]<-216
Salta$TotalLeg[ Salta$Circuito == "42A" & Salta$Year ==0]<-999
Salta$TotalLeg[ Salta$Circuito == "42B" & Salta$Year ==0]<-1302.5
Salta$TotalLeg[ Salta$Circuito == "42C" & Salta$Year ==0]<-7956
Salta$TotalLeg[ Salta$Circuito == "43A" & Salta$Year ==0]<-20827.5
Salta$TotalLeg[ Salta$Circuito == "43B" & Salta$Year ==0]<-1326
Salta$TotalLeg[ Salta$Circuito == "43C" & Salta$Year ==0]<-2735
Salta$TotalLeg[ Salta$Circuito == "43D" & Salta$Year ==0]<-165
Salta$TotalLeg[ Salta$Circuito == "43E" & Salta$Year ==0]<-2537
Salta$TotalLeg[ Salta$Circuito == "43F" & Salta$Year ==0]<-654
Salta$TotalLeg[ Salta$Circuito == "44A" & Salta$Year ==0]<-4262
Salta$TotalLeg[ Salta$Circuito == "44B" & Salta$Year ==0]<-376
Salta$TotalLeg[ Salta$Circuito == "44C" & Salta$Year ==0]<-467
Salta$TotalLeg[ Salta$Circuito == "44D" & Salta$Year ==0]<-443
Salta$TotalLeg[ Salta$Circuito == "44E" & Salta$Year ==0]<-459
Salta$TotalLeg[ Salta$Circuito == "44F" & Salta$Year ==0]<-279
Salta$TotalLeg[ Salta$Circuito == "44G" & Salta$Year ==0]<-227
Salta$TotalLeg[ Salta$Circuito == "45A" & Salta$Year ==0]<-8289
Salta$TotalLeg[ Salta$Circuito == "46A" & Salta$Year ==0]<-557
Salta$TotalLeg[ Salta$Circuito == "46B" & Salta$Year ==0]<-204
Salta$TotalLeg[ Salta$Circuito == "46C" & Salta$Year ==0]<-109
Salta$TotalLeg[ Salta$Circuito == "46D" & Salta$Year ==0]<-265
Salta$TotalLeg[ Salta$Circuito == "46E" & Salta$Year ==0]<-44
Salta$TotalLeg[ Salta$Circuito == "46F" & Salta$Year ==0]<-303
Salta$TotalLeg[ Salta$Circuito == "46G" & Salta$Year ==0]<-74
Salta$TotalLeg[ Salta$Circuito == "46H" & Salta$Year ==0]<-119
Salta$TotalLeg[ Salta$Circuito == "47A" & Salta$Year ==0]<-124
Salta$TotalLeg[ Salta$Circuito == "47B" & Salta$Year ==0]<-93
Salta$TotalLeg[ Salta$Circuito == "47C" & Salta$Year ==0]<-56
Salta$TotalLeg[ Salta$Circuito == "48A" & Salta$Year ==0]<-48
Salta$TotalLeg[ Salta$Circuito == "48B" & Salta$Year ==0]<-83
Salta$TotalLeg[ Salta$Circuito == "48C" & Salta$Year ==0]<-885
Salta$TotalLeg[ Salta$Circuito == "48D" & Salta$Year ==0]<-210
Salta$TotalLeg[ Salta$Circuito == "49A" & Salta$Year ==0]<-689.5
Salta$TotalLeg[ Salta$Circuito == "49B" & Salta$Year ==0]<-105
Salta$TotalLeg[ Salta$Circuito == "49C" & Salta$Year ==0]<-109
Salta$TotalLeg[ Salta$Circuito == "49D" & Salta$Year ==0]<-178
Salta$TotalLeg[ Salta$Circuito == "49E" & Salta$Year ==0]<-180
Salta$TotalLeg[ Salta$Circuito == "49F" & Salta$Year ==0]<-152
Salta$TotalLeg[ Salta$Circuito == "49G" & Salta$Year ==0]<-301
Salta$TotalLeg[ Salta$Circuito == "49H" & Salta$Year ==0]<-97
Salta$TotalLeg[ Salta$Circuito == "49I" & Salta$Year ==0]<-115
Salta$TotalLeg[ Salta$Circuito == "49J" & Salta$Year ==0]<-323
Salta$TotalLeg[ Salta$Circuito == "49K" & Salta$Year ==0]<-140
Salta$TotalLeg[ Salta$Circuito == "50A" & Salta$Year ==0]<-906
Salta$TotalLeg[ Salta$Circuito == "50B" & Salta$Year ==0]<-285
Salta$TotalLeg[ Salta$Circuito == "50C" & Salta$Year ==0]<-126
Salta$TotalLeg[ Salta$Circuito == "51A" & Salta$Year ==0]<-713.5
Salta$TotalLeg[ Salta$Circuito == "51B" & Salta$Year ==0]<-93
Salta$TotalLeg[ Salta$Circuito == "51D" & Salta$Year ==0]<-133
Salta$TotalLeg[ Salta$Circuito == "51E" & Salta$Year ==0]<-60
Salta$TotalLeg[ Salta$Circuito == "51F" & Salta$Year ==0]<-48
Salta$TotalLeg[ Salta$Circuito == "52A" & Salta$Year ==0]<-3909
Salta$TotalLeg[ Salta$Circuito == "52B" & Salta$Year ==0]<-2591
Salta$TotalLeg[ Salta$Circuito == "52C" & Salta$Year ==0]<-351
Salta$TotalLeg[ Salta$Circuito == "52D" & Salta$Year ==0]<-262
Salta$TotalLeg[ Salta$Circuito == "53A" & Salta$Year ==0]<-1426
Salta$TotalLeg[ Salta$Circuito == "53B" & Salta$Year ==0]<-569
Salta$TotalLeg[ Salta$Circuito == "54A" & Salta$Year ==0]<-4009
Salta$TotalLeg[ Salta$Circuito == "54B" & Salta$Year ==0]<-178
Salta$TotalLeg[ Salta$Circuito == "55A" & Salta$Year ==0]<-574
Salta$TotalLeg[ Salta$Circuito == "55B" & Salta$Year ==0]<-236
Salta$TotalLeg[ Salta$Circuito == "55C" & Salta$Year ==0]<-118
Salta$TotalLeg[ Salta$Circuito == "59A" & Salta$Year ==0]<-1508
Salta$TotalLeg[ Salta$Circuito == "5A" & Salta$Year ==0]<-4396
Salta$TotalLeg[ Salta$Circuito == "5B" & Salta$Year ==0]<-4323
Salta$TotalLeg[ Salta$Circuito == "5C" & Salta$Year ==0]<-4186
Salta$TotalLeg[ Salta$Circuito == "5E" & Salta$Year ==0]<-7271
Salta$TotalLeg[ Salta$Circuito == "5F" & Salta$Year ==0]<-5606
Salta$TotalLeg[ Salta$Circuito == "5G" & Salta$Year ==0]<-6333
Salta$TotalLeg[ Salta$Circuito == "5I" & Salta$Year ==0]<-7513
Salta$TotalLeg[ Salta$Circuito == "5J" & Salta$Year ==0]<-449
Salta$TotalLeg[ Salta$Circuito == "5K" & Salta$Year ==0]<-877
Salta$TotalLeg[ Salta$Circuito == "5L" & Salta$Year ==0]<-4402
Salta$TotalLeg[ Salta$Circuito == "5M" & Salta$Year ==0]<-740
Salta$TotalLeg[ Salta$Circuito == "5N" & Salta$Year ==0]<-2099
Salta$TotalLeg[ Salta$Circuito == "60A" & Salta$Year ==0]<-249
Salta$TotalLeg[ Salta$Circuito == "61A" & Salta$Year ==0]<-2463
Salta$TotalLeg[ Salta$Circuito == "62A" & Salta$Year ==0]<-239
Salta$TotalLeg[ Salta$Circuito == "63A" & Salta$Year ==0]<-1412
Salta$TotalLeg[ Salta$Circuito == "64A" & Salta$Year ==0]<-24
Salta$TotalLeg[ Salta$Circuito == "64B" & Salta$Year ==0]<-70
Salta$TotalLeg[ Salta$Circuito == "65A" & Salta$Year ==0]<-83
Salta$TotalLeg[ Salta$Circuito == "65B" & Salta$Year ==0]<-100
Salta$TotalLeg[ Salta$Circuito == "66A" & Salta$Year ==0]<-141
Salta$TotalLeg[ Salta$Circuito == "66B" & Salta$Year ==0]<-155
Salta$TotalLeg[ Salta$Circuito == "67A" & Salta$Year ==0]<-9525
Salta$TotalLeg[ Salta$Circuito == "67B" & Salta$Year ==0]<-2378
Salta$TotalLeg[ Salta$Circuito == "67C" & Salta$Year ==0]<-283
Salta$TotalLeg[ Salta$Circuito == "67D" & Salta$Year ==0]<-317
Salta$TotalLeg[ Salta$Circuito == "67E" & Salta$Year ==0]<-147
Salta$TotalLeg[ Salta$Circuito == "67F" & Salta$Year ==0]<-71
Salta$TotalLeg[ Salta$Circuito == "67G" & Salta$Year ==0]<-120
Salta$TotalLeg[ Salta$Circuito == "67H" & Salta$Year ==0]<-113
Salta$TotalLeg[ Salta$Circuito == "68A" & Salta$Year ==0]<-92
Salta$TotalLeg[ Salta$Circuito == "68B" & Salta$Year ==0]<-96
Salta$TotalLeg[ Salta$Circuito == "68C" & Salta$Year ==0]<-67
Salta$TotalLeg[ Salta$Circuito == "69A" & Salta$Year ==0]<-119
Salta$TotalLeg[ Salta$Circuito == "6A" & Salta$Year ==0]<-3271
Salta$TotalLeg[ Salta$Circuito == "70A" & Salta$Year ==0]<-119
Salta$TotalLeg[ Salta$Circuito == "70B" & Salta$Year ==0]<-139
Salta$TotalLeg[ Salta$Circuito == "71A" & Salta$Year ==0]<-467
Salta$TotalLeg[ Salta$Circuito == "71B" & Salta$Year ==0]<-76
Salta$TotalLeg[ Salta$Circuito == "72A" & Salta$Year ==0]<-378
Salta$TotalLeg[ Salta$Circuito == "72B" & Salta$Year ==0]<-114
Salta$TotalLeg[ Salta$Circuito == "72C" & Salta$Year ==0]<-331
Salta$TotalLeg[ Salta$Circuito == "72D" & Salta$Year ==0]<-194
Salta$TotalLeg[ Salta$Circuito == "73A" & Salta$Year ==0]<-515
Salta$TotalLeg[ Salta$Circuito == "73B" & Salta$Year ==0]<-236
Salta$TotalLeg[ Salta$Circuito == "74A" & Salta$Year ==0]<-1673
Salta$TotalLeg[ Salta$Circuito == "75A" & Salta$Year ==0]<-952
Salta$TotalLeg[ Salta$Circuito == "75B" & Salta$Year ==0]<-211
Salta$TotalLeg[ Salta$Circuito == "79A" & Salta$Year ==0]<-1273
Salta$TotalLeg[ Salta$Circuito == "79B" & Salta$Year ==0]<-921
Salta$TotalLeg[ Salta$Circuito == "79C" & Salta$Year ==0]<-208
Salta$TotalLeg[ Salta$Circuito == "7A" & Salta$Year ==0]<-101
Salta$TotalLeg[ Salta$Circuito == "80A" & Salta$Year ==0]<-110
Salta$TotalLeg[ Salta$Circuito == "81A" & Salta$Year ==0]<-233
Salta$TotalLeg[ Salta$Circuito == "82A" & Salta$Year ==0]<-668
Salta$TotalLeg[ Salta$Circuito == "82B" & Salta$Year ==0]<-109
Salta$TotalLeg[ Salta$Circuito == "83A" & Salta$Year ==0]<-155
Salta$TotalLeg[ Salta$Circuito == "83B" & Salta$Year ==0]<-252
Salta$TotalLeg[ Salta$Circuito == "84A" & Salta$Year ==0]<-664
Salta$TotalLeg[ Salta$Circuito == "85A" & Salta$Year ==0]<-609
Salta$TotalLeg[ Salta$Circuito == "85B" & Salta$Year ==0]<-93
Salta$TotalLeg[ Salta$Circuito == "86A" & Salta$Year ==0]<-597
Salta$TotalLeg[ Salta$Circuito == "87A" & Salta$Year ==0]<-336
Salta$TotalLeg[ Salta$Circuito == "88A" & Salta$Year ==0]<-188
Salta$TotalLeg[ Salta$Circuito == "88B" & Salta$Year ==0]<-68
Salta$TotalLeg[ Salta$Circuito == "88C" & Salta$Year ==0]<-272
Salta$TotalLeg[ Salta$Circuito == "91A" & Salta$Year ==0]<-9472
Salta$TotalLeg[ Salta$Circuito == "91B" & Salta$Year ==0]<-436
Salta$TotalLeg[ Salta$Circuito == "91C" & Salta$Year ==0]<-219
Salta$TotalLeg[ Salta$Circuito == "91D" & Salta$Year ==0]<-163
Salta$TotalLeg[ Salta$Circuito == "92A" & Salta$Year ==0]<-162
Salta$TotalLeg[ Salta$Circuito == "93A" & Salta$Year ==0]<-4538
Salta$TotalLeg[ Salta$Circuito == "93B" & Salta$Year ==0]<-84
Salta$TotalLeg[ Salta$Circuito == "94A" & Salta$Year ==0]<-172
Salta$TotalLeg[ Salta$Circuito == "95A" & Salta$Year ==0]<-1550
Salta$TotalLeg[ Salta$Circuito == "96B" & Salta$Year ==0]<-113
Salta$TotalLeg[ Salta$Circuito == "97A" & Salta$Year ==0]<-109
Salta$TotalLeg[ Salta$Circuito == "97B" & Salta$Year ==0]<-110
Salta$TotalLeg[ Salta$Circuito == "97C" & Salta$Year ==0]<-97
Salta$TotalLeg[ Salta$Circuito == "97D" & Salta$Year ==0]<-50
Salta$TotalLeg[ Salta$Circuito == "98A" & Salta$Year ==0]<-62
Salta$TotalLeg[ Salta$Circuito == "99A" & Salta$Year ==0]<-505
Salta$TotalLeg[ Salta$Circuito == "99B" & Salta$Year ==0]<-207
Salta$TotalLeg[ Salta$Circuito == "99C" & Salta$Year ==0]<-304
Salta$TotalLeg[ Salta$Circuito == "9A" & Salta$Year ==0]<-2662
Salta$TotalLeg[ Salta$Circuito == "9B" & Salta$Year ==0]<-205
Salta$TotalLeg[ Salta$Circuito == "100A" & Salta$Year ==1]<-2485
Salta$TotalLeg[ Salta$Circuito == "101A" & Salta$Year ==1]<-112
Salta$TotalLeg[ Salta$Circuito == "102A" & Salta$Year ==1]<-137
Salta$TotalLeg[ Salta$Circuito == "103A" & Salta$Year ==1]<-112
Salta$TotalLeg[ Salta$Circuito == "103B" & Salta$Year ==1]<-16
Salta$TotalLeg[ Salta$Circuito == "10A" & Salta$Year ==1]<-2929
Salta$TotalLeg[ Salta$Circuito == "11A" & Salta$Year ==1]<-2748
Salta$TotalLeg[ Salta$Circuito == "11B" & Salta$Year ==1]<-473
Salta$TotalLeg[ Salta$Circuito == "11C" & Salta$Year ==1]<-441
Salta$TotalLeg[ Salta$Circuito == "12A" & Salta$Year ==1]<-5703
Salta$TotalLeg[ Salta$Circuito == "12B" & Salta$Year ==1]<-4753
Salta$TotalLeg[ Salta$Circuito == "12C" & Salta$Year ==1]<-4102
Salta$TotalLeg[ Salta$Circuito == "13A" & Salta$Year ==1]<-137
Salta$TotalLeg[ Salta$Circuito == "16A" & Salta$Year ==1]<-927
Salta$TotalLeg[ Salta$Circuito == "16B" & Salta$Year ==1]<-295
Salta$TotalLeg[ Salta$Circuito == "17A" & Salta$Year ==1]<-2535
Salta$TotalLeg[ Salta$Circuito == "17B" & Salta$Year ==1]<-124
Salta$TotalLeg[ Salta$Circuito == "18A" & Salta$Year ==1]<-207
Salta$TotalLeg[ Salta$Circuito == "18B" & Salta$Year ==1]<-360
Salta$TotalLeg[ Salta$Circuito == "18C" & Salta$Year ==1]<-83
Salta$TotalLeg[ Salta$Circuito == "19A" & Salta$Year ==1]<-82
Salta$TotalLeg[ Salta$Circuito == "21A" & Salta$Year ==1]<-4597
Salta$TotalLeg[ Salta$Circuito == "21B" & Salta$Year ==1]<-360
Salta$TotalLeg[ Salta$Circuito == "22A" & Salta$Year ==1]<-3800
Salta$TotalLeg[ Salta$Circuito == "22B" & Salta$Year ==1]<-251
Salta$TotalLeg[ Salta$Circuito == "22C" & Salta$Year ==1]<-555
Salta$TotalLeg[ Salta$Circuito == "22D" & Salta$Year ==1]<-490
Salta$TotalLeg[ Salta$Circuito == "22E" & Salta$Year ==1]<-825
Salta$TotalLeg[ Salta$Circuito == "23A" & Salta$Year ==1]<-134
Salta$TotalLeg[ Salta$Circuito == "24A" & Salta$Year ==1]<-7651
Salta$TotalLeg[ Salta$Circuito == "24B" & Salta$Year ==1]<-324
Salta$TotalLeg[ Salta$Circuito == "24C" & Salta$Year ==1]<-237
Salta$TotalLeg[ Salta$Circuito == "24D" & Salta$Year ==1]<-248
Salta$TotalLeg[ Salta$Circuito == "24E" & Salta$Year ==1]<-609
Salta$TotalLeg[ Salta$Circuito == "24G" & Salta$Year ==1]<-140
Salta$TotalLeg[ Salta$Circuito == "25A" & Salta$Year ==1]<-3952
Salta$TotalLeg[ Salta$Circuito == "25B" & Salta$Year ==1]<-86
Salta$TotalLeg[ Salta$Circuito == "25C" & Salta$Year ==1]<-578
Salta$TotalLeg[ Salta$Circuito == "25D" & Salta$Year ==1]<-1050
Salta$TotalLeg[ Salta$Circuito == "25E" & Salta$Year ==1]<-359
Salta$TotalLeg[ Salta$Circuito == "25F" & Salta$Year ==1]<-80
Salta$TotalLeg[ Salta$Circuito == "25G" & Salta$Year ==1]<-50
Salta$TotalLeg[ Salta$Circuito == "26A" & Salta$Year ==1]<-382
Salta$TotalLeg[ Salta$Circuito == "26B" & Salta$Year ==1]<-1387
Salta$TotalLeg[ Salta$Circuito == "27A" & Salta$Year ==1]<-1431
Salta$TotalLeg[ Salta$Circuito == "27B" & Salta$Year ==1]<-310
Salta$TotalLeg[ Salta$Circuito == "28A" & Salta$Year ==1]<-208
Salta$TotalLeg[ Salta$Circuito == "28B" & Salta$Year ==1]<-2418
Salta$TotalLeg[ Salta$Circuito == "28C" & Salta$Year ==1]<-117
Salta$TotalLeg[ Salta$Circuito == "28D" & Salta$Year ==1]<-79
Salta$TotalLeg[ Salta$Circuito == "28E" & Salta$Year ==1]<-738
Salta$TotalLeg[ Salta$Circuito == "28F" & Salta$Year ==1]<-355
Salta$TotalLeg[ Salta$Circuito == "28G" & Salta$Year ==1]<-88
Salta$TotalLeg[ Salta$Circuito == "29A" & Salta$Year ==1]<-913
Salta$TotalLeg[ Salta$Circuito == "29B" & Salta$Year ==1]<-19
Salta$TotalLeg[ Salta$Circuito == "29C" & Salta$Year ==1]<-1807
Salta$TotalLeg[ Salta$Circuito == "29D" & Salta$Year ==1]<-77
Salta$TotalLeg[ Salta$Circuito == "29E" & Salta$Year ==1]<-621
Salta$TotalLeg[ Salta$Circuito == "29F" & Salta$Year ==1]<-557
Salta$TotalLeg[ Salta$Circuito == "29G" & Salta$Year ==1]<-561
Salta$TotalLeg[ Salta$Circuito == "29H" & Salta$Year ==1]<-181
Salta$TotalLeg[ Salta$Circuito == "2D" & Salta$Year ==1]<-6112
Salta$TotalLeg[ Salta$Circuito == "2G" & Salta$Year ==1]<-6473
Salta$TotalLeg[ Salta$Circuito == "2H" & Salta$Year ==1]<-1541
Salta$TotalLeg[ Salta$Circuito == "2I" & Salta$Year ==1]<-6530
Salta$TotalLeg[ Salta$Circuito == "2J" & Salta$Year ==1]<-5822
Salta$TotalLeg[ Salta$Circuito == "2K" & Salta$Year ==1]<-4066
Salta$TotalLeg[ Salta$Circuito == "2L" & Salta$Year ==1]<-3905
Salta$TotalLeg[ Salta$Circuito == "2N" & Salta$Year ==1]<-5276
Salta$TotalLeg[ Salta$Circuito == "2O" & Salta$Year ==1]<-5289
Salta$TotalLeg[ Salta$Circuito == "2P" & Salta$Year ==1]<-3687
Salta$TotalLeg[ Salta$Circuito == "2Q" & Salta$Year ==1]<-6526
Salta$TotalLeg[ Salta$Circuito == "32A" & Salta$Year ==1]<-944
Salta$TotalLeg[ Salta$Circuito == "32B" & Salta$Year ==1]<-4886
Salta$TotalLeg[ Salta$Circuito == "34A" & Salta$Year ==1]<-5812
Salta$TotalLeg[ Salta$Circuito == "34B" & Salta$Year ==1]<-42
Salta$TotalLeg[ Salta$Circuito == "35A" & Salta$Year ==1]<-1713
Salta$TotalLeg[ Salta$Circuito == "36A" & Salta$Year ==1]<-228
Salta$TotalLeg[ Salta$Circuito == "36B" & Salta$Year ==1]<-9546
Salta$TotalLeg[ Salta$Circuito == "37A" & Salta$Year ==1]<-96
Salta$TotalLeg[ Salta$Circuito == "38A" & Salta$Year ==1]<-102
Salta$TotalLeg[ Salta$Circuito == "38B" & Salta$Year ==1]<-135
Salta$TotalLeg[ Salta$Circuito == "39A" & Salta$Year ==1]<-108
Salta$TotalLeg[ Salta$Circuito == "3G" & Salta$Year ==1]<-5831
Salta$TotalLeg[ Salta$Circuito == "3H" & Salta$Year ==1]<-5619
Salta$TotalLeg[ Salta$Circuito == "3I" & Salta$Year ==1]<-5840
Salta$TotalLeg[ Salta$Circuito == "3J" & Salta$Year ==1]<-1977
Salta$TotalLeg[ Salta$Circuito == "40A" & Salta$Year ==1]<-8812
Salta$TotalLeg[ Salta$Circuito == "40B" & Salta$Year ==1]<-903
Salta$TotalLeg[ Salta$Circuito == "40C" & Salta$Year ==1]<-133
Salta$TotalLeg[ Salta$Circuito == "41A" & Salta$Year ==1]<-1167.5
Salta$TotalLeg[ Salta$Circuito == "41B" & Salta$Year ==1]<-898.5
Salta$TotalLeg[ Salta$Circuito == "41C" & Salta$Year ==1]<-328
Salta$TotalLeg[ Salta$Circuito == "41D" & Salta$Year ==1]<-122.5
Salta$TotalLeg[ Salta$Circuito == "42A" & Salta$Year ==1]<-854.5
Salta$TotalLeg[ Salta$Circuito == "42B" & Salta$Year ==1]<-1285.5
Salta$TotalLeg[ Salta$Circuito == "42C" & Salta$Year ==1]<-7303.5
Salta$TotalLeg[ Salta$Circuito == "43A" & Salta$Year ==1]<-19330
Salta$TotalLeg[ Salta$Circuito == "43B" & Salta$Year ==1]<-1079.5
Salta$TotalLeg[ Salta$Circuito == "43C" & Salta$Year ==1]<-2832.5
Salta$TotalLeg[ Salta$Circuito == "43D" & Salta$Year ==1]<-129.5
Salta$TotalLeg[ Salta$Circuito == "43E" & Salta$Year ==1]<-2829
Salta$TotalLeg[ Salta$Circuito == "43F" & Salta$Year ==1]<-685.5
Salta$TotalLeg[ Salta$Circuito == "44A" & Salta$Year ==1]<-4161
Salta$TotalLeg[ Salta$Circuito == "44B" & Salta$Year ==1]<-403.5
Salta$TotalLeg[ Salta$Circuito == "44C" & Salta$Year ==1]<-513.5
Salta$TotalLeg[ Salta$Circuito == "44D" & Salta$Year ==1]<-389
Salta$TotalLeg[ Salta$Circuito == "44E" & Salta$Year ==1]<-495.5
Salta$TotalLeg[ Salta$Circuito == "44F" & Salta$Year ==1]<-282
Salta$TotalLeg[ Salta$Circuito == "44G" & Salta$Year ==1]<-226
Salta$TotalLeg[ Salta$Circuito == "45A" & Salta$Year ==1]<-8619.5
Salta$TotalLeg[ Salta$Circuito == "46A" & Salta$Year ==1]<-600
Salta$TotalLeg[ Salta$Circuito == "46B" & Salta$Year ==1]<-180
Salta$TotalLeg[ Salta$Circuito == "46C" & Salta$Year ==1]<-48
Salta$TotalLeg[ Salta$Circuito == "46D" & Salta$Year ==1]<-241
Salta$TotalLeg[ Salta$Circuito == "46E" & Salta$Year ==1]<-28
Salta$TotalLeg[ Salta$Circuito == "46F" & Salta$Year ==1]<-323
Salta$TotalLeg[ Salta$Circuito == "46G" & Salta$Year ==1]<-54
Salta$TotalLeg[ Salta$Circuito == "46H" & Salta$Year ==1]<-100
Salta$TotalLeg[ Salta$Circuito == "47A" & Salta$Year ==1]<-82
Salta$TotalLeg[ Salta$Circuito == "47B" & Salta$Year ==1]<-80
Salta$TotalLeg[ Salta$Circuito == "47C" & Salta$Year ==1]<-47
Salta$TotalLeg[ Salta$Circuito == "48A" & Salta$Year ==1]<-28
Salta$TotalLeg[ Salta$Circuito == "48B" & Salta$Year ==1]<-67
Salta$TotalLeg[ Salta$Circuito == "48C" & Salta$Year ==1]<-836
Salta$TotalLeg[ Salta$Circuito == "48D" & Salta$Year ==1]<-198
Salta$TotalLeg[ Salta$Circuito == "49A" & Salta$Year ==1]<-707
Salta$TotalLeg[ Salta$Circuito == "49B" & Salta$Year ==1]<-74
Salta$TotalLeg[ Salta$Circuito == "49C" & Salta$Year ==1]<-68
Salta$TotalLeg[ Salta$Circuito == "49D" & Salta$Year ==1]<-119
Salta$TotalLeg[ Salta$Circuito == "49E" & Salta$Year ==1]<-147.5
Salta$TotalLeg[ Salta$Circuito == "49F" & Salta$Year ==1]<-149
Salta$TotalLeg[ Salta$Circuito == "49G" & Salta$Year ==1]<-244.5
Salta$TotalLeg[ Salta$Circuito == "49H" & Salta$Year ==1]<-97
Salta$TotalLeg[ Salta$Circuito == "49I" & Salta$Year ==1]<-95
Salta$TotalLeg[ Salta$Circuito == "49J" & Salta$Year ==1]<-316.5
Salta$TotalLeg[ Salta$Circuito == "49K" & Salta$Year ==1]<-131
Salta$TotalLeg[ Salta$Circuito == "50A" & Salta$Year ==1]<-975
Salta$TotalLeg[ Salta$Circuito == "50B" & Salta$Year ==1]<-276
Salta$TotalLeg[ Salta$Circuito == "50C" & Salta$Year ==1]<-120
Salta$TotalLeg[ Salta$Circuito == "51A" & Salta$Year ==1]<-746.5
Salta$TotalLeg[ Salta$Circuito == "51B" & Salta$Year ==1]<-387
Salta$TotalLeg[ Salta$Circuito == "51D" & Salta$Year ==1]<-136
Salta$TotalLeg[ Salta$Circuito == "51E" & Salta$Year ==1]<-43.5
Salta$TotalLeg[ Salta$Circuito == "51F" & Salta$Year ==1]<-44
Salta$TotalLeg[ Salta$Circuito == "52A" & Salta$Year ==1]<-4023
Salta$TotalLeg[ Salta$Circuito == "52B" & Salta$Year ==1]<-2706
Salta$TotalLeg[ Salta$Circuito == "52C" & Salta$Year ==1]<-366.5
Salta$TotalLeg[ Salta$Circuito == "52D" & Salta$Year ==1]<-229.5
Salta$TotalLeg[ Salta$Circuito == "53A" & Salta$Year ==1]<-1578.5
Salta$TotalLeg[ Salta$Circuito == "53B" & Salta$Year ==1]<-875.5
Salta$TotalLeg[ Salta$Circuito == "54A" & Salta$Year ==1]<-4127.5
Salta$TotalLeg[ Salta$Circuito == "54B" & Salta$Year ==1]<-154
Salta$TotalLeg[ Salta$Circuito == "55A" & Salta$Year ==1]<-642
Salta$TotalLeg[ Salta$Circuito == "55B" & Salta$Year ==1]<-224.5
Salta$TotalLeg[ Salta$Circuito == "55C" & Salta$Year ==1]<-120
Salta$TotalLeg[ Salta$Circuito == "59A" & Salta$Year ==1]<-1500.5
Salta$TotalLeg[ Salta$Circuito == "5A" & Salta$Year ==1]<-4920
Salta$TotalLeg[ Salta$Circuito == "5B" & Salta$Year ==1]<-4034
Salta$TotalLeg[ Salta$Circuito == "5C" & Salta$Year ==1]<-4883
Salta$TotalLeg[ Salta$Circuito == "5E" & Salta$Year ==1]<-9039
Salta$TotalLeg[ Salta$Circuito == "5F" & Salta$Year ==1]<-6304
Salta$TotalLeg[ Salta$Circuito == "5G" & Salta$Year ==1]<-6383
Salta$TotalLeg[ Salta$Circuito == "5I" & Salta$Year ==1]<-7837
Salta$TotalLeg[ Salta$Circuito == "5J" & Salta$Year ==1]<-518
Salta$TotalLeg[ Salta$Circuito == "5K" & Salta$Year ==1]<-1071
Salta$TotalLeg[ Salta$Circuito == "5L" & Salta$Year ==1]<-5298
Salta$TotalLeg[ Salta$Circuito == "5M" & Salta$Year ==1]<-1589
Salta$TotalLeg[ Salta$Circuito == "5N" & Salta$Year ==1]<-3493
Salta$TotalLeg[ Salta$Circuito == "60A" & Salta$Year ==1]<-223.5
Salta$TotalLeg[ Salta$Circuito == "61A" & Salta$Year ==1]<-2473
Salta$TotalLeg[ Salta$Circuito == "62A" & Salta$Year ==1]<-174.5
Salta$TotalLeg[ Salta$Circuito == "63A" & Salta$Year ==1]<-1581
Salta$TotalLeg[ Salta$Circuito == "64A" & Salta$Year ==1]<-19
Salta$TotalLeg[ Salta$Circuito == "64B" & Salta$Year ==1]<-73
Salta$TotalLeg[ Salta$Circuito == "65A" & Salta$Year ==1]<-85
Salta$TotalLeg[ Salta$Circuito == "65B" & Salta$Year ==1]<-90
Salta$TotalLeg[ Salta$Circuito == "66A" & Salta$Year ==1]<-148
Salta$TotalLeg[ Salta$Circuito == "66B" & Salta$Year ==1]<-157
Salta$TotalLeg[ Salta$Circuito == "67A" & Salta$Year ==1]<-8681
Salta$TotalLeg[ Salta$Circuito == "67B" & Salta$Year ==1]<-2871
Salta$TotalLeg[ Salta$Circuito == "67C" & Salta$Year ==1]<-179
Salta$TotalLeg[ Salta$Circuito == "67D" & Salta$Year ==1]<-269
Salta$TotalLeg[ Salta$Circuito == "67E" & Salta$Year ==1]<-116
Salta$TotalLeg[ Salta$Circuito == "67F" & Salta$Year ==1]<-47
Salta$TotalLeg[ Salta$Circuito == "67G" & Salta$Year ==1]<-90
Salta$TotalLeg[ Salta$Circuito == "67H" & Salta$Year ==1]<-98
Salta$TotalLeg[ Salta$Circuito == "68A" & Salta$Year ==1]<-53
Salta$TotalLeg[ Salta$Circuito == "68B" & Salta$Year ==1]<-68
Salta$TotalLeg[ Salta$Circuito == "68C" & Salta$Year ==1]<-38
Salta$TotalLeg[ Salta$Circuito == "69A" & Salta$Year ==1]<-74
Salta$TotalLeg[ Salta$Circuito == "6A" & Salta$Year ==1]<-3511
Salta$TotalLeg[ Salta$Circuito == "70A" & Salta$Year ==1]<-81
Salta$TotalLeg[ Salta$Circuito == "70B" & Salta$Year ==1]<-107
Salta$TotalLeg[ Salta$Circuito == "71A" & Salta$Year ==1]<-396
Salta$TotalLeg[ Salta$Circuito == "71B" & Salta$Year ==1]<-65
Salta$TotalLeg[ Salta$Circuito == "72A" & Salta$Year ==1]<-355
Salta$TotalLeg[ Salta$Circuito == "72B" & Salta$Year ==1]<-67
Salta$TotalLeg[ Salta$Circuito == "72C" & Salta$Year ==1]<-289
Salta$TotalLeg[ Salta$Circuito == "72D" & Salta$Year ==1]<-187
Salta$TotalLeg[ Salta$Circuito == "73A" & Salta$Year ==1]<-485.5
Salta$TotalLeg[ Salta$Circuito == "73B" & Salta$Year ==1]<-212
Salta$TotalLeg[ Salta$Circuito == "74A" & Salta$Year ==1]<-1664.5
Salta$TotalLeg[ Salta$Circuito == "75A" & Salta$Year ==1]<-967
Salta$TotalLeg[ Salta$Circuito == "75B" & Salta$Year ==1]<-188
Salta$TotalLeg[ Salta$Circuito == "79A" & Salta$Year ==1]<-1316
Salta$TotalLeg[ Salta$Circuito == "79B" & Salta$Year ==1]<-863
Salta$TotalLeg[ Salta$Circuito == "79C" & Salta$Year ==1]<-190
Salta$TotalLeg[ Salta$Circuito == "7A" & Salta$Year ==1]<-82
Salta$TotalLeg[ Salta$Circuito == "80A" & Salta$Year ==1]<-90
Salta$TotalLeg[ Salta$Circuito == "81A" & Salta$Year ==1]<-212
Salta$TotalLeg[ Salta$Circuito == "82A" & Salta$Year ==1]<-620
Salta$TotalLeg[ Salta$Circuito == "82B" & Salta$Year ==1]<-82
Salta$TotalLeg[ Salta$Circuito == "83A" & Salta$Year ==1]<-109
Salta$TotalLeg[ Salta$Circuito == "83B" & Salta$Year ==1]<-212
Salta$TotalLeg[ Salta$Circuito == "84A" & Salta$Year ==1]<-713
Salta$TotalLeg[ Salta$Circuito == "85A" & Salta$Year ==1]<-645
Salta$TotalLeg[ Salta$Circuito == "85B" & Salta$Year ==1]<-73
Salta$TotalLeg[ Salta$Circuito == "86A" & Salta$Year ==1]<-584
Salta$TotalLeg[ Salta$Circuito == "87A" & Salta$Year ==1]<-374
Salta$TotalLeg[ Salta$Circuito == "88A" & Salta$Year ==1]<-179
Salta$TotalLeg[ Salta$Circuito == "88B" & Salta$Year ==1]<-66
Salta$TotalLeg[ Salta$Circuito == "88C" & Salta$Year ==1]<-277
Salta$TotalLeg[ Salta$Circuito == "91A" & Salta$Year ==1]<-9711
Salta$TotalLeg[ Salta$Circuito == "91B" & Salta$Year ==1]<-362
Salta$TotalLeg[ Salta$Circuito == "91C" & Salta$Year ==1]<-187
Salta$TotalLeg[ Salta$Circuito == "91D" & Salta$Year ==1]<-189
Salta$TotalLeg[ Salta$Circuito == "92A" & Salta$Year ==1]<-136
Salta$TotalLeg[ Salta$Circuito == "93A" & Salta$Year ==1]<-4706
Salta$TotalLeg[ Salta$Circuito == "93B" & Salta$Year ==1]<-76
Salta$TotalLeg[ Salta$Circuito == "94A" & Salta$Year ==1]<-140
Salta$TotalLeg[ Salta$Circuito == "95A" & Salta$Year ==1]<-1612
Salta$TotalLeg[ Salta$Circuito == "96B" & Salta$Year ==1]<-70
Salta$TotalLeg[ Salta$Circuito == "97A" & Salta$Year ==1]<-82
Salta$TotalLeg[ Salta$Circuito == "97B" & Salta$Year ==1]<-89
Salta$TotalLeg[ Salta$Circuito == "97C" & Salta$Year ==1]<-88
Salta$TotalLeg[ Salta$Circuito == "97D" & Salta$Year ==1]<-30
Salta$TotalLeg[ Salta$Circuito == "98A" & Salta$Year ==1]<-59
Salta$TotalLeg[ Salta$Circuito == "99A" & Salta$Year ==1]<-565
Salta$TotalLeg[ Salta$Circuito == "99B" & Salta$Year ==1]<-212
Salta$TotalLeg[ Salta$Circuito == "99C" & Salta$Year ==1]<-282
Salta$TotalLeg[ Salta$Circuito == "9A" & Salta$Year ==1]<-2894
Salta$TotalLeg[ Salta$Circuito == "9B" & Salta$Year ==1]<-205
Salta$TotalLeg[ Salta$Circuito == "15A" & Salta$Year ==0]<-3065
Salta$TotalLeg[ Salta$Circuito == "15B" & Salta$Year ==0]<-2365
Salta$TotalLeg[ Salta$Circuito == "15C" & Salta$Year ==0]<-3804
Salta$TotalLeg[ Salta$Circuito == "15D" & Salta$Year ==0]<-4182
Salta$TotalLeg[ Salta$Circuito == "15E" & Salta$Year ==0]<-415
Salta$TotalLeg[ Salta$Circuito == "15F" & Salta$Year ==0]<-159
Salta$TotalLeg[ Salta$Circuito == "15G" & Salta$Year ==0]<-199
Salta$TotalLeg[ Salta$Circuito == "1A" & Salta$Year ==0]<-3162
Salta$TotalLeg[ Salta$Circuito == "1B" & Salta$Year ==0]<-2859
Salta$TotalLeg[ Salta$Circuito == "1C" & Salta$Year ==0]<-2896
Salta$TotalLeg[ Salta$Circuito == "1D" & Salta$Year ==0]<-3634
Salta$TotalLeg[ Salta$Circuito == "1E" & Salta$Year ==0]<-3406
Salta$TotalLeg[ Salta$Circuito == "1F" & Salta$Year ==0]<-6397
Salta$TotalLeg[ Salta$Circuito == "1G" & Salta$Year ==0]<-5396
Salta$TotalLeg[ Salta$Circuito == "2A" & Salta$Year ==0]<-5650
Salta$TotalLeg[ Salta$Circuito == "2B" & Salta$Year ==0]<-3237
Salta$TotalLeg[ Salta$Circuito == "2C" & Salta$Year ==0]<-4395
Salta$TotalLeg[ Salta$Circuito == "2E" & Salta$Year ==0]<-2295
Salta$TotalLeg[ Salta$Circuito == "2F" & Salta$Year ==0]<-4861
Salta$TotalLeg[ Salta$Circuito == "2M" & Salta$Year ==0]<-4764
Salta$TotalLeg[ Salta$Circuito == "30A" & Salta$Year ==0]<-822
Salta$TotalLeg[ Salta$Circuito == "30B" & Salta$Year ==0]<-1137
Salta$TotalLeg[ Salta$Circuito == "31A" & Salta$Year ==0]<-18828
Salta$TotalLeg[ Salta$Circuito == "31B" & Salta$Year ==0]<-12015
Salta$TotalLeg[ Salta$Circuito == "31C" & Salta$Year ==0]<-383
Salta$TotalLeg[ Salta$Circuito == "33A" & Salta$Year ==0]<-200
Salta$TotalLeg[ Salta$Circuito == "33B" & Salta$Year ==0]<-330
Salta$TotalLeg[ Salta$Circuito == "3A" & Salta$Year ==0]<-7874
Salta$TotalLeg[ Salta$Circuito == "3B" & Salta$Year ==0]<-12806
Salta$TotalLeg[ Salta$Circuito == "3C" & Salta$Year ==0]<-6036
Salta$TotalLeg[ Salta$Circuito == "3D" & Salta$Year ==0]<-4153
Salta$TotalLeg[ Salta$Circuito == "3E" & Salta$Year ==0]<-4622
Salta$TotalLeg[ Salta$Circuito == "3F" & Salta$Year ==0]<-5294
Salta$TotalLeg[ Salta$Circuito == "3K" & Salta$Year ==0]<-1373
Salta$TotalLeg[ Salta$Circuito == "4A" & Salta$Year ==0]<-3941
Salta$TotalLeg[ Salta$Circuito == "4B" & Salta$Year ==0]<-460
Salta$TotalLeg[ Salta$Circuito == "4C" & Salta$Year ==0]<-1251
Salta$TotalLeg[ Salta$Circuito == "5D" & Salta$Year ==0]<-3809
Salta$TotalLeg[ Salta$Circuito == "5H" & Salta$Year ==0]<-2944
Salta$TotalLeg[ Salta$Circuito == "8A" & Salta$Year ==0]<-1383
Salta$TotalLeg[ Salta$Circuito == "8B" & Salta$Year ==0]<-122
Salta$TotalLeg[ Salta$Circuito == "8C" & Salta$Year ==0]<-123
Salta$TotalLeg[ Salta$Circuito == "15A" & Salta$Year ==1]<-2994
Salta$TotalLeg[ Salta$Circuito == "15B" & Salta$Year ==1]<-1606
Salta$TotalLeg[ Salta$Circuito == "15C" & Salta$Year ==1]<-3596
Salta$TotalLeg[ Salta$Circuito == "15D" & Salta$Year ==1]<-4196
Salta$TotalLeg[ Salta$Circuito == "15E" & Salta$Year ==1]<-354
Salta$TotalLeg[ Salta$Circuito == "15F" & Salta$Year ==1]<-668
Salta$TotalLeg[ Salta$Circuito == "15G" & Salta$Year ==1]<-146
Salta$TotalLeg[ Salta$Circuito == "1A" & Salta$Year ==1]<-3375
Salta$TotalLeg[ Salta$Circuito == "1B" & Salta$Year ==1]<-2244
Salta$TotalLeg[ Salta$Circuito == "1C" & Salta$Year ==1]<-2777
Salta$TotalLeg[ Salta$Circuito == "1D" & Salta$Year ==1]<-3355
Salta$TotalLeg[ Salta$Circuito == "1E" & Salta$Year ==1]<-3164
Salta$TotalLeg[ Salta$Circuito == "1F" & Salta$Year ==1]<-6743
Salta$TotalLeg[ Salta$Circuito == "1G" & Salta$Year ==1]<-5227
Salta$TotalLeg[ Salta$Circuito == "2A" & Salta$Year ==1]<-5300
Salta$TotalLeg[ Salta$Circuito == "2B" & Salta$Year ==1]<-3111
Salta$TotalLeg[ Salta$Circuito == "2C" & Salta$Year ==1]<-3726
Salta$TotalLeg[ Salta$Circuito == "2E" & Salta$Year ==1]<-1708
Salta$TotalLeg[ Salta$Circuito == "2F" & Salta$Year ==1]<-4415
Salta$TotalLeg[ Salta$Circuito == "2M" & Salta$Year ==1]<-4970
Salta$TotalLeg[ Salta$Circuito == "30A" & Salta$Year ==1]<-587
Salta$TotalLeg[ Salta$Circuito == "30B" & Salta$Year ==1]<-1122
Salta$TotalLeg[ Salta$Circuito == "31A" & Salta$Year ==1]<-17717
Salta$TotalLeg[ Salta$Circuito == "31B" & Salta$Year ==1]<-11942
Salta$TotalLeg[ Salta$Circuito == "31C" & Salta$Year ==1]<-315
Salta$TotalLeg[ Salta$Circuito == "33A" & Salta$Year ==1]<-139
Salta$TotalLeg[ Salta$Circuito == "33B" & Salta$Year ==1]<-131
Salta$TotalLeg[ Salta$Circuito == "3A" & Salta$Year ==1]<-9136
Salta$TotalLeg[ Salta$Circuito == "3B" & Salta$Year ==1]<-13520
Salta$TotalLeg[ Salta$Circuito == "3C" & Salta$Year ==1]<-6199
Salta$TotalLeg[ Salta$Circuito == "3D" & Salta$Year ==1]<-4445
Salta$TotalLeg[ Salta$Circuito == "3E" & Salta$Year ==1]<-4133
Salta$TotalLeg[ Salta$Circuito == "3F" & Salta$Year ==1]<-4855
Salta$TotalLeg[ Salta$Circuito == "3K" & Salta$Year ==1]<-2260
Salta$TotalLeg[ Salta$Circuito == "4A" & Salta$Year ==1]<-4796
Salta$TotalLeg[ Salta$Circuito == "4B" & Salta$Year ==1]<-516
Salta$TotalLeg[ Salta$Circuito == "4C" & Salta$Year ==1]<-1822
Salta$TotalLeg[ Salta$Circuito == "5D" & Salta$Year ==1]<-4566
Salta$TotalLeg[ Salta$Circuito == "5H" & Salta$Year ==1]<-3245
Salta$TotalLeg[ Salta$Circuito == "8A" & Salta$Year ==1]<-1624
Salta$TotalLeg[ Salta$Circuito == "8B" & Salta$Year ==1]<-109
Salta$TotalLeg[ Salta$Circuito == "8C" & Salta$Year ==1]<-93

#VOLVER A SCRIPT ANALYSIS TESIS
file.edit("https://github.com/TuQmano/evoteSALTA_UTDT/blob/master/analysis.R")
